//==============================================================================
// Symbols.cpp
//==============================================================================
#include "stdafx.h"

namespace Gurax {

//------------------------------------------------------------------------------
// Predefined Symbols
//------------------------------------------------------------------------------
Gurax_RealizeSymbol(__cast__);
Gurax_RealizeSymbol(__del__);
Gurax_RealizeSymbol(__file__);
Gurax_RealizeSymbol(__init__);
Gurax_RealizeSymbol(__line__);
Gurax_RealizeSymbol(__name__);
Gurax_RealizeSymbol(__root__);
Gurax_RealizeSymbol(__tmpl__);
Gurax_RealizeSymbol(a);
Gurax_RealizeSymbol(A);
Gurax_RealizeSymbol(abs);
Gurax_RealizeSymbol(add);
Gurax_RealizeSymbol(addr);
Gurax_RealizeSymbol(addr8);
Gurax_RealizeSymbol(addr16);
Gurax_RealizeSymbol(addr24);
Gurax_RealizeSymbol(addr32);
Gurax_RealizeSymbol(addr40);
Gurax_RealizeSymbol(addr48);
Gurax_RealizeSymbol(addr56);
Gurax_RealizeSymbol(addr64);
Gurax_RealizeSymbol(addrInfo);
Gurax_RealizeSymbol(addSep);
Gurax_RealizeSymbol(align);
Gurax_RealizeSymbol(all);
Gurax_RealizeSymbol(alpha);
Gurax_RealizeSymbol(and);
Gurax_RealizeSymbol(any);
Gurax_RealizeSymbol(anyAttr);
Gurax_RealizeSymbol(aqua);
Gurax_RealizeSymbol(ar);
Gurax_RealizeSymbol(arg);
Gurax_RealizeSymbol(argument);
Gurax_RealizeSymbol(argSymbols);
Gurax_RealizeSymbol(array);
Gurax_RealizeSymbol(ascend);
Gurax_RealizeSymbol(ascii);
Gurax_RealizeSymbol(asctime);
Gurax_RealizeSymbol(asSource);
Gurax_RealizeSymbol(asssign);
Gurax_RealizeSymbol(asValue);
Gurax_RealizeSymbolAlias(at_bool, "@bool");
Gurax_RealizeSymbolAlias(at_int8, "@int8");
Gurax_RealizeSymbolAlias(at_int16, "@int16");
Gurax_RealizeSymbolAlias(at_int32, "@int32");
Gurax_RealizeSymbolAlias(at_int64, "@int64");
Gurax_RealizeSymbolAlias(at_half, "@half");
Gurax_RealizeSymbolAlias(at_float, "@float");
Gurax_RealizeSymbolAlias(at_double, "@double");
Gurax_RealizeSymbolAlias(at_complex, "@complex");
Gurax_RealizeSymbolAlias(at_uint8, "@uint8");
Gurax_RealizeSymbolAlias(at_uint16, "@uint16");
Gurax_RealizeSymbolAlias(at_uint32, "@uint32");
Gurax_RealizeSymbolAlias(at_uint64, "@uint64");
Gurax_RealizeSymbolAlias(at_char, "@char");
Gurax_RealizeSymbolAlias(at_uchar, "@uchar");
Gurax_RealizeSymbolAlias(at_short, "@short");
Gurax_RealizeSymbolAlias(at_ushort, "@ushort");
Gurax_RealizeSymbolAlias(at_int, "@int");
Gurax_RealizeSymbolAlias(at_uint, "@uint");
Gurax_RealizeSymbolAlias(at_long, "@long");
Gurax_RealizeSymbolAlias(at_ulong, "@ulong");
Gurax_RealizeSymbol(attrFront);
Gurax_RealizeSymbol(attrs);
Gurax_RealizeSymbol(attrsOpt);
Gurax_RealizeSymbol(audio);
Gurax_RealizeSymbol(audioType);
Gurax_RealizeSymbolAlias(auto_, "auto");
Gurax_RealizeSymbol(autoIndent);
Gurax_RealizeSymbol(b);
Gurax_RealizeSymbol(B);
Gurax_RealizeSymbol(background);
Gurax_RealizeSymbol(backward);
Gurax_RealizeSymbol(base16);
Gurax_RealizeSymbol(base32);
Gurax_RealizeSymbol(base32hex);
Gurax_RealizeSymbol(base64);
Gurax_RealizeSymbol(basic);
Gurax_RealizeSymbol(bcc);
Gurax_RealizeSymbol(be);
Gurax_RealizeSymbol(begin);
Gurax_RealizeSymbol(bfs);
Gurax_RealizeSymbol(bg);
Gurax_RealizeSymbol(bgr);
Gurax_RealizeSymbol(bgra);
Gurax_RealizeSymbol(bias);
Gurax_RealizeSymbol(biased);
Gurax_RealizeSymbol(binary);
Gurax_RealizeSymbol(bitmap);
Gurax_RealizeSymbol(bitsPerSample);
Gurax_RealizeSymbol(black);
Gurax_RealizeSymbol(block);
Gurax_RealizeSymbol(blockParam);
Gurax_RealizeSymbol(blue);
Gurax_RealizeSymbol(body);
Gurax_RealizeSymbolAlias(bool_, "bool");
Gurax_RealizeSymbol(boolean);
Gurax_RealizeSymbol(both);
Gurax_RealizeSymbol(bottom);
Gurax_RealizeSymbol(boundary);
Gurax_RealizeSymbol(box);
Gurax_RealizeSymbol(bracket);
Gurax_RealizeSymbolAlias(break_, "break");
Gurax_RealizeSymbol(brief);
Gurax_RealizeSymbol(brightAqua);
Gurax_RealizeSymbol(brightBlue);
Gurax_RealizeSymbol(brightCyan);
Gurax_RealizeSymbol(brightGreen);
Gurax_RealizeSymbol(brightMagenta);
Gurax_RealizeSymbol(brightPurple);
Gurax_RealizeSymbol(brightRed);
Gurax_RealizeSymbol(brightWhite);
Gurax_RealizeSymbol(brightYellow);
Gurax_RealizeSymbol(byte);
Gurax_RealizeSymbol(bytes);
Gurax_RealizeSymbol(bytesPerSample);
Gurax_RealizeSymbol(bz2);
Gurax_RealizeSymbol(bzip2);
Gurax_RealizeSymbol(c);
Gurax_RealizeSymbol(C);
Gurax_RealizeSymbol(car);
Gurax_RealizeSymbol(cArray);
Gurax_RealizeSymbolAlias(case_, "case");
Gurax_RealizeSymbol(cast);
Gurax_RealizeSymbolAlias(catch_, "catch");
Gurax_RealizeSymbol(cdr);
Gurax_RealizeSymbol(center);
Gurax_RealizeSymbol(channels);
Gurax_RealizeSymbolAlias(char_, "char");
Gurax_RealizeSymbol(child);
Gurax_RealizeSymbol(children);
Gurax_RealizeSymbol(chop);
Gurax_RealizeSymbol(clang);
Gurax_RealizeSymbolAlias(class_, "class");
Gurax_RealizeSymbol(classMethod);
Gurax_RealizeSymbol(close);
Gurax_RealizeSymbol(closure);
Gurax_RealizeSymbol(cm);
Gurax_RealizeSymbol(codec);
Gurax_RealizeSymbol(codecs);
Gurax_RealizeSymbol(color);
Gurax_RealizeSymbol(column);
Gurax_RealizeSymbol(common);
Gurax_RealizeSymbol(complex);
Gurax_RealizeSymbolAlias(const_, "const");
Gurax_RealizeSymbol(container);
Gurax_RealizeSymbolAlias(continue_, "continue");
Gurax_RealizeSymbol(cooked);
Gurax_RealizeSymbol(cos);
Gurax_RealizeSymbol(cram);
Gurax_RealizeSymbol(crammed);
Gurax_RealizeSymbol(cross);
Gurax_RealizeSymbol(cs);
Gurax_RealizeSymbol(cstr);
Gurax_RealizeSymbol(cur);
Gurax_RealizeSymbol(cutExtraArgs);
Gurax_RealizeSymbol(cyan);
Gurax_RealizeSymbol(d);
Gurax_RealizeSymbol(D);
Gurax_RealizeSymbol(darwin);
Gurax_RealizeSymbol(datetime);
Gurax_RealizeSymbol(day);
Gurax_RealizeSymbol(days);
Gurax_RealizeSymbol(de);
Gurax_RealizeSymbol(decl);
Gurax_RealizeSymbol(declaration);
Gurax_RealizeSymbol(decls);
Gurax_RealizeSymbolAlias(default_, "default");
Gurax_RealizeSymbol(deg);
Gurax_RealizeSymbol(delta);
Gurax_RealizeSymbolAlias(delete_, "delete");
Gurax_RealizeSymbol(denom);
Gurax_RealizeSymbol(depth);
Gurax_RealizeSymbol(descend);
Gurax_RealizeSymbol(device);
Gurax_RealizeSymbol(dfs);
Gurax_RealizeSymbol(dict);
Gurax_RealizeSymbol(dir);
Gurax_RealizeSymbol(directory);
Gurax_RealizeSymbol(doc);
Gurax_RealizeSymbol(document);
Gurax_RealizeSymbolAlias(double_, "double");
Gurax_RealizeSymbol(Double);
Gurax_RealizeSymbol(down);
Gurax_RealizeSymbol(dquoteString);
Gurax_RealizeSymbol(dynamicScope);
Gurax_RealizeSymbol(e);
Gurax_RealizeSymbol(E);
Gurax_RealizeSymbol(elemtype);
Gurax_RealizeSymbol(elimSep);
Gurax_RealizeSymbolAlias(else_, "else");
Gurax_RealizeSymbol(elsif);
Gurax_RealizeSymbol(en);
Gurax_RealizeSymbol(end);
Gurax_RealizeSymbol(endMarker);
Gurax_RealizeSymbol(environment);
Gurax_RealizeSymbol(eof);
Gurax_RealizeSymbol(eol);
Gurax_RealizeSymbol(error);
Gurax_RealizeSymbol(esc);
Gurax_RealizeSymbol(exp);
Gurax_RealizeSymbol(expr);
Gurax_RealizeSymbolAlias(extern_, "extern");
Gurax_RealizeSymbol(f);
Gurax_RealizeSymbol(F);
Gurax_RealizeSymbolAlias(false_, "false");
Gurax_RealizeSymbol(fancy);
Gurax_RealizeSymbol(fg);
Gurax_RealizeSymbol(fifo);
Gurax_RealizeSymbol(file);
Gurax_RealizeSymbol(finalize);
Gurax_RealizeSymbol(finalizer);
Gurax_RealizeSymbol(finally);
Gurax_RealizeSymbol(first);
Gurax_RealizeSymbol(firstEol);
Gurax_RealizeSymbol(flat);
Gurax_RealizeSymbolAlias(float_, "float");
Gurax_RealizeSymbol(Float);
Gurax_RealizeSymbol(flloat);
Gurax_RealizeSymbol(followLink);
Gurax_RealizeSymbolAlias(for_, "for");
Gurax_RealizeSymbol(force);
Gurax_RealizeSymbol(foreground);
Gurax_RealizeSymbol(fork);
Gurax_RealizeSymbol(format);
Gurax_RealizeSymbol(formatter);
Gurax_RealizeSymbol(forward);
Gurax_RealizeSymbol(fr);
Gurax_RealizeSymbol(Fri);
Gurax_RealizeSymbol(Friday);
Gurax_RealizeSymbol(ftp);
Gurax_RealizeSymbol(fullname);
Gurax_RealizeSymbol(function);
Gurax_RealizeSymbol(funcScope);
Gurax_RealizeSymbol(g);
Gurax_RealizeSymbol(G);
Gurax_RealizeSymbol(gear);
Gurax_RealizeSymbol(gnuc);
Gurax_RealizeSymbol(gray);
Gurax_RealizeSymbol(green);
Gurax_RealizeSymbol(gz);
Gurax_RealizeSymbol(gzip);
Gurax_RealizeSymbol(h);
Gurax_RealizeSymbol(H);
Gurax_RealizeSymbol(half);
Gurax_RealizeSymbol(head);
Gurax_RealizeSymbol(height);
Gurax_RealizeSymbol(help);
Gurax_RealizeSymbol(horz);
Gurax_RealizeSymbol(host);
Gurax_RealizeSymbol(hour);
Gurax_RealizeSymbol(http);
Gurax_RealizeSymbol(hybrid);
Gurax_RealizeSymbol(i);
Gurax_RealizeSymbol(I);
Gurax_RealizeSymbol(icase);
Gurax_RealizeSymbol(identifier);
Gurax_RealizeSymbolAlias(if_, "if");
Gurax_RealizeSymbol(imag);
Gurax_RealizeSymbol(image);
Gurax_RealizeSymbol(imageType);
Gurax_RealizeSymbol(inch);
Gurax_RealizeSymbol(indent);
Gurax_RealizeSymbol(index);
Gurax_RealizeSymbol(indices);
Gurax_RealizeSymbol(input);
Gurax_RealizeSymbol(inputLeft);
Gurax_RealizeSymbol(inputRight);
Gurax_RealizeSymbol(inputGrad);
Gurax_RealizeSymbol(inputGradLeft);
Gurax_RealizeSymbol(inputGradRight);
Gurax_RealizeSymbol(insideScope);
Gurax_RealizeSymbol(instance);
Gurax_RealizeSymbolAlias(int_, "int");
Gurax_RealizeSymbol(int8);
Gurax_RealizeSymbol(int16);
Gurax_RealizeSymbol(int32);
Gurax_RealizeSymbol(int64);
Gurax_RealizeSymbol(invalid);
Gurax_RealizeSymbol(item);
Gurax_RealizeSymbol(iter);
Gurax_RealizeSymbol(iterator);
Gurax_RealizeSymbol(iterItem);
Gurax_RealizeSymbol(j);
Gurax_RealizeSymbol(J);
Gurax_RealizeSymbol(ja);
Gurax_RealizeSymbol(k);
Gurax_RealizeSymbol(K);
Gurax_RealizeSymbol(ka);
Gurax_RealizeSymbol(keep);
Gurax_RealizeSymbol(ko);
Gurax_RealizeSymbol(l);
Gurax_RealizeSymbol(L);
Gurax_RealizeSymbol(lang);
Gurax_RealizeSymbol(langCode);
Gurax_RealizeSymbol(last);
Gurax_RealizeSymbol(lastEol);
Gurax_RealizeSymbol(lastIndex);
Gurax_RealizeSymbol(le);
Gurax_RealizeSymbol(leader);
Gurax_RealizeSymbol(left);
Gurax_RealizeSymbol(leftBottom);
Gurax_RealizeSymbol(LeftBottomHorz);
Gurax_RealizeSymbol(LeftBottomVert);
Gurax_RealizeSymbol(leftTop);
Gurax_RealizeSymbol(LeftTopHorz);
Gurax_RealizeSymbol(LeftTopVert);
Gurax_RealizeSymbol(len);
Gurax_RealizeSymbol(lexer);
Gurax_RealizeSymbolAlias(line_, "line");
Gurax_RealizeSymbol(lineNo);
Gurax_RealizeSymbol(lineNoBottom);
Gurax_RealizeSymbol(link);
Gurax_RealizeSymbolAlias(linux_, "linux");
Gurax_RealizeSymbol(list);
Gurax_RealizeSymbol(listItem);
Gurax_RealizeSymbol(listVar);
Gurax_RealizeSymbol(local);
Gurax_RealizeSymbol(log);
Gurax_RealizeSymbolAlias(long_, "long");
Gurax_RealizeSymbol(loose);
Gurax_RealizeSymbol(lower);
Gurax_RealizeSymbol(lowerCase);
Gurax_RealizeSymbol(m);
Gurax_RealizeSymbol(M);
Gurax_RealizeSymbol(magenta);
Gurax_RealizeSymbol(map);
Gurax_RealizeSymbol(mapAlong);
Gurax_RealizeSymbol(mapToIter);
Gurax_RealizeSymbol(mapToList);
Gurax_RealizeSymbol(math);
Gurax_RealizeSymbol(mathBinary);
Gurax_RealizeSymbol(mathUnary);
Gurax_RealizeSymbol(matrix);
Gurax_RealizeSymbol(message);
Gurax_RealizeSymbol(method);
Gurax_RealizeSymbol(min);
Gurax_RealizeSymbol(minus);
Gurax_RealizeSymbol(misc);
Gurax_RealizeSymbol(mixinType);
Gurax_RealizeSymbol(mm);
Gurax_RealizeSymbol(mode);
Gurax_RealizeSymbol(Mon);
Gurax_RealizeSymbol(Monday);
Gurax_RealizeSymbol(monitor);
Gurax_RealizeSymbol(mono);
Gurax_RealizeSymbol(month);
Gurax_RealizeSymbol(msc);
Gurax_RealizeSymbol(msec);
Gurax_RealizeSymbol(msecs);
Gurax_RealizeSymbol(mswin);
Gurax_RealizeSymbol(multi);
Gurax_RealizeSymbol(multiLine);
Gurax_RealizeSymbol(n);
Gurax_RealizeSymbol(N);
Gurax_RealizeSymbol(name);
Gurax_RealizeSymbol(ndim);
Gurax_RealizeSymbol(neat);
Gurax_RealizeSymbol(next);
Gurax_RealizeSymbolAlias(new_, "new");
Gurax_RealizeSymbol(nil);
Gurax_RealizeSymbol(nilVisible);
Gurax_RealizeSymbol(noCast);
Gurax_RealizeSymbol(noEscape);
Gurax_RealizeSymbol(noFlat);
Gurax_RealizeSymbol(noIndent);
Gurax_RealizeSymbol(noMap);
Gurax_RealizeSymbol(noNamed);
Gurax_RealizeSymbol(none);
Gurax_RealizeSymbol(norm);
Gurax_RealizeSymbol(normal);
Gurax_RealizeSymbol(noSort);
Gurax_RealizeSymbol(nsec);
Gurax_RealizeSymbol(nsecs);
Gurax_RealizeSymbol(number);
Gurax_RealizeSymbol(numer);
Gurax_RealizeSymbol(o);
Gurax_RealizeSymbol(O);
Gurax_RealizeSymbol(object);
Gurax_RealizeSymbol(offset);
Gurax_RealizeSymbol(oneLine);
Gurax_RealizeSymbol(open);
Gurax_RealizeSymbol(openL);
Gurax_RealizeSymbol(openR);
Gurax_RealizeSymbolAlias(operator_, "operator");
Gurax_RealizeSymbol(or);
Gurax_RealizeSymbol(output);
Gurax_RealizeSymbol(outputGrad);
Gurax_RealizeSymbol(overwrite);
Gurax_RealizeSymbol(p);
Gurax_RealizeSymbol(P);
Gurax_RealizeSymbol(padding);
Gurax_RealizeSymbol(palette);
Gurax_RealizeSymbol(parent);
Gurax_RealizeSymbol(parents);
Gurax_RealizeSymbol(part);
Gurax_RealizeSymbol(partly);
Gurax_RealizeSymbol(password);
Gurax_RealizeSymbol(path);
Gurax_RealizeSymbol(pathname);
Gurax_RealizeSymbol(percent);
Gurax_RealizeSymbol(pi);
Gurax_RealizeSymbol(pixel);
Gurax_RealizeSymbol(pl);
Gurax_RealizeSymbol(plus);
Gurax_RealizeSymbol(pointer);
Gurax_RealizeSymbol(port);
Gurax_RealizeSymbol(post);
Gurax_RealizeSymbol(posText);
Gurax_RealizeSymbol(pre);
Gurax_RealizeSymbol(prec);
Gurax_RealizeSymbol(prefix);
Gurax_RealizeSymbol(prev);
Gurax_RealizeSymbol(previous);
Gurax_RealizeSymbolAlias(private_, "private");
Gurax_RealizeSymbol(privileged);
Gurax_RealizeSymbolAlias(protected_, "protected");
Gurax_RealizeSymbol(ps1);
Gurax_RealizeSymbol(ps2);
Gurax_RealizeSymbolAlias(public_, "public");
Gurax_RealizeSymbol(purple);
Gurax_RealizeSymbol(q);
Gurax_RealizeSymbol(Q);
Gurax_RealizeSymbol(query);
Gurax_RealizeSymbol(quote);
Gurax_RealizeSymbol(quoteString);
Gurax_RealizeSymbol(qq);
Gurax_RealizeSymbol(r);
Gurax_RealizeSymbol(R);
Gurax_RealizeSymbol(raise);
Gurax_RealizeSymbol(ratio);
Gurax_RealizeSymbol(raw);
Gurax_RealizeSymbol(read);
Gurax_RealizeSymbol(readable);
Gurax_RealizeSymbol(real);
Gurax_RealizeSymbol(red);
Gurax_RealizeSymbol(reduce);
Gurax_RealizeSymbol(relu);
Gurax_RealizeSymbol(repeat);
Gurax_RealizeSymbol(rest);
Gurax_RealizeSymbol(rev);
Gurax_RealizeSymbol(rgb);
Gurax_RealizeSymbol(rgba);
Gurax_RealizeSymbol(rgbq);
Gurax_RealizeSymbol(right);
Gurax_RealizeSymbol(rightBottom);
Gurax_RealizeSymbol(RightBottomHorz);
Gurax_RealizeSymbol(RightBottomVert);
Gurax_RealizeSymbol(rightTop);
Gurax_RealizeSymbol(RightTopHorz);
Gurax_RealizeSymbol(RightTopVert);
Gurax_RealizeSymbol(root);
Gurax_RealizeSymbol(row);
Gurax_RealizeSymbol(s);
Gurax_RealizeSymbol(S);
Gurax_RealizeSymbol(s16be);
Gurax_RealizeSymbol(s16le);
Gurax_RealizeSymbol(s32be);
Gurax_RealizeSymbol(s32le);
Gurax_RealizeSymbol(s64be);
Gurax_RealizeSymbol(s64le);
Gurax_RealizeSymbol(s8);
Gurax_RealizeSymbol(same);
Gurax_RealizeSymbol(sample);
Gurax_RealizeSymbol(samples);
Gurax_RealizeSymbol(samplespersec);
Gurax_RealizeSymbol(Sat);
Gurax_RealizeSymbol(Saturday);
Gurax_RealizeSymbol(scheme);
Gurax_RealizeSymbol(sec);
Gurax_RealizeSymbol(secs);
Gurax_RealizeSymbol(semaphore);
Gurax_RealizeSymbol(set);
Gurax_RealizeSymbol(shape);
Gurax_RealizeSymbolAlias(short_, "short");
Gurax_RealizeSymbol(shrink);
Gurax_RealizeSymbol(shrinkable);
Gurax_RealizeSymbol(sibling);
Gurax_RealizeSymbol(siblings);
Gurax_RealizeSymbol(sigmoid);
Gurax_RealizeSymbol(sin);
Gurax_RealizeSymbol(single);
Gurax_RealizeSymbol(singleLine);
Gurax_RealizeSymbol(size);
Gurax_RealizeSymbolAlias(size_at_all, "size@all");
Gurax_RealizeSymbol(socket);
Gurax_RealizeSymbol(sort);
Gurax_RealizeSymbol(source);
Gurax_RealizeSymbol(space);
Gurax_RealizeSymbol(sqrt);
Gurax_RealizeSymbol(stable);
Gurax_RealizeSymbol(statement);
Gurax_RealizeSymbol(stat);
Gurax_RealizeSymbolAlias(static_, "static");
Gurax_RealizeSymbol(stay);
Gurax_RealizeSymbolAlias(stderr_, "stderr");
Gurax_RealizeSymbolAlias(stdin_, "stdin");
Gurax_RealizeSymbolAlias(stdout_, "stdout");
Gurax_RealizeSymbol(sticky);
Gurax_RealizeSymbolAlias(sticky_at_top, "sticky@top");
Gurax_RealizeSymbolAlias(sticky_at_btm, "sticky@btm");
Gurax_RealizeSymbol(stream);
Gurax_RealizeSymbol(strict);
Gurax_RealizeSymbol(string);
Gurax_RealizeSymbol(stringCast);
Gurax_RealizeSymbol(stringUnquoted);
Gurax_RealizeSymbol(suffix);
Gurax_RealizeSymbol(suffixmgr);
Gurax_RealizeSymbol(Sun);
Gurax_RealizeSymbol(Sunday);
Gurax_RealizeSymbol(super);
Gurax_RealizeSymbol(surround);
Gurax_RealizeSymbol(sv);
Gurax_RealizeSymbol(symbol);
Gurax_RealizeSymbol(symbolFunc);
Gurax_RealizeSymbol(quoteSymbol);
Gurax_RealizeSymbol(symbolUnquoted);
Gurax_RealizeSymbol(t);
Gurax_RealizeSymbol(T);
Gurax_RealizeSymbol(target);
Gurax_RealizeSymbolAlias(template_, "template");
Gurax_RealizeSymbol(text);
Gurax_RealizeSymbolAlias(this_, "this");
Gurax_RealizeSymbol(Thu);
Gurax_RealizeSymbol(Thursday);
Gurax_RealizeSymbol(timeDelta);
Gurax_RealizeSymbol(timid);
Gurax_RealizeSymbol(title);
Gurax_RealizeSymbol(top);
Gurax_RealizeSymbol(trace);
Gurax_RealizeSymbol(trailer);
Gurax_RealizeSymbol(transpose);
Gurax_RealizeSymbol(tree);
Gurax_RealizeSymbolAlias(true_, "true");
Gurax_RealizeSymbolAlias(try_, "try");
Gurax_RealizeSymbol(Tue);
Gurax_RealizeSymbol(Tuesday);
Gurax_RealizeSymbol(type);
Gurax_RealizeSymbolAlias(typename_, "typename");
Gurax_RealizeSymbol(typesym);
Gurax_RealizeSymbol(u);
Gurax_RealizeSymbol(U);
Gurax_RealizeSymbol(u16be);
Gurax_RealizeSymbol(u16le);
Gurax_RealizeSymbol(u32be);
Gurax_RealizeSymbol(u32le);
Gurax_RealizeSymbol(u64be);
Gurax_RealizeSymbol(u64le);
Gurax_RealizeSymbol(u8);
Gurax_RealizeSymbol(uchar);
Gurax_RealizeSymbol(uint);
Gurax_RealizeSymbol(uint8);
Gurax_RealizeSymbol(uint16);
Gurax_RealizeSymbol(uint32);
Gurax_RealizeSymbol(uint64);
Gurax_RealizeSymbol(ulong);
Gurax_RealizeSymbol(unary);
Gurax_RealizeSymbol(unaryPost);
Gurax_RealizeSymbol(unbias);
Gurax_RealizeSymbol(unbiased);
Gurax_RealizeSymbol(unbracket);
Gurax_RealizeSymbol(unit);
Gurax_RealizeSymbol(unitstep);
Gurax_RealizeSymbolAlias(unix_, "unix");
Gurax_RealizeSymbol(unixtime);
Gurax_RealizeSymbol(unknown);
Gurax_RealizeSymbol(up);
Gurax_RealizeSymbol(upper);
Gurax_RealizeSymbol(upperCase);
Gurax_RealizeSymbol(uri);
Gurax_RealizeSymbol(url);
Gurax_RealizeSymbol(urlpath);
Gurax_RealizeSymbol(usec);
Gurax_RealizeSymbol(usecs);
Gurax_RealizeSymbol(user);
Gurax_RealizeSymbol(ushort);
Gurax_RealizeSymbol(utc);
Gurax_RealizeSymbol(utf16);
Gurax_RealizeSymbol(utf32);
Gurax_RealizeSymbol(utf8);
Gurax_RealizeSymbol(v);
Gurax_RealizeSymbol(V);
Gurax_RealizeSymbol(valid);
Gurax_RealizeSymbol(value);
Gurax_RealizeSymbol(values);
Gurax_RealizeSymbol(verbose);
Gurax_RealizeSymbol(vert);
Gurax_RealizeSymbol(vertex);
Gurax_RealizeSymbolAlias(void_, "void");
Gurax_RealizeSymbol(w);
Gurax_RealizeSymbol(W);
Gurax_RealizeSymbol(w3c);
Gurax_RealizeSymbol(wday);
Gurax_RealizeSymbol(web);
Gurax_RealizeSymbol(websafe);
Gurax_RealizeSymbol(Wed);
Gurax_RealizeSymbol(Wednesday);
Gurax_RealizeSymbol(week);
Gurax_RealizeSymbolAlias(while_, "while");
Gurax_RealizeSymbol(white);
Gurax_RealizeSymbol(width);
Gurax_RealizeSymbol(win);
Gurax_RealizeSymbol(win256);
Gurax_RealizeSymbol(window);
Gurax_RealizeSymbol(windows);
Gurax_RealizeSymbol(write);
Gurax_RealizeSymbol(writable);
Gurax_RealizeSymbol(x);
Gurax_RealizeSymbol(X);
Gurax_RealizeSymbol(xiter);
Gurax_RealizeSymbol(xiterItem);
Gurax_RealizeSymbol(xlist);
Gurax_RealizeSymbol(xlistItem);
Gurax_RealizeSymbol(xor);
Gurax_RealizeSymbol(xreduce);
Gurax_RealizeSymbol(xset);
Gurax_RealizeSymbol(y);
Gurax_RealizeSymbol(Y);
Gurax_RealizeSymbol(yday);
Gurax_RealizeSymbol(year);
Gurax_RealizeSymbol(yellow);
Gurax_RealizeSymbol(z);
Gurax_RealizeSymbol(Z);
Gurax_RealizeSymbol(zero);
Gurax_RealizeSymbol(zh);
Gurax_RealizeSymbol(zip);

//------------------------------------------------------------------------------
// Predefined Symbol Marks
//------------------------------------------------------------------------------
Gurax_RealizeSymbolMark(As,					"as");
Gurax_RealizeSymbolMark(Assign,				"=");
Gurax_RealizeSymbolMark(AssignAdd,			"+=");
Gurax_RealizeSymbolMark(AssignSub,			"-=");
Gurax_RealizeSymbolMark(AssignMul,			"*=");
Gurax_RealizeSymbolMark(AssignDiv,			"/=");
Gurax_RealizeSymbolMark(AssignMod,			"%=");
Gurax_RealizeSymbolMark(AssignPow,			"**=");
Gurax_RealizeSymbolMark(AssignOr,			"|=");
Gurax_RealizeSymbolMark(AssignAnd,			"&=");
Gurax_RealizeSymbolMark(AssignXor,			"^=");
Gurax_RealizeSymbolMark(AssignShl,			"<<=");
Gurax_RealizeSymbolMark(AssignShr,			">>=");
Gurax_RealizeSymbolMark(Pair,				"=>");
Gurax_RealizeSymbolMark(OrOr,				"||");
Gurax_RealizeSymbolMark(AndAnd,				"&&");
Gurax_RealizeSymbolMark(Not,				"!");
Gurax_RealizeSymbolMark(Contains,			"in");
Gurax_RealizeSymbolMark(Lt,					"<");
Gurax_RealizeSymbolMark(Gt,					">");
Gurax_RealizeSymbolMark(Le,					"<=");
Gurax_RealizeSymbolMark(Ge,					">=");
Gurax_RealizeSymbolMark(Cmp,				"<=>");
Gurax_RealizeSymbolMark(Eq,					"==");
Gurax_RealizeSymbolMark(Ne,					"!=");
Gurax_RealizeSymbolMark(Seq,				"..");
Gurax_RealizeSymbolMark(Or,					"|");
Gurax_RealizeSymbolMark(Xor,				"^");
Gurax_RealizeSymbolMark(And,				"&");
Gurax_RealizeSymbolMark(Shl,				"<<");
Gurax_RealizeSymbolMark(Shr,				">>");
Gurax_RealizeSymbolMark(Add,				"+");
Gurax_RealizeSymbolMark(Sub,				"-");
Gurax_RealizeSymbolMark(Mul,				"*");
Gurax_RealizeSymbolMark(Div,				"/");
Gurax_RealizeSymbolMark(Mod,				"%");
Gurax_RealizeSymbolMark(ModMod,				"%%");
Gurax_RealizeSymbolMark(Dot,				"|.|");
Gurax_RealizeSymbolMark(Cross,				"|^|");
Gurax_RealizeSymbolMark(Gear,				"|*|");
Gurax_RealizeSymbolMark(Concat,				"|+|");
Gurax_RealizeSymbolMark(Difference,			"|-|");
Gurax_RealizeSymbolMark(Intersection,		"|&|");
Gurax_RealizeSymbolMark(Union,				"|||");
Gurax_RealizeSymbolMark(Question,			"?");
Gurax_RealizeSymbolMark(Inv,				"~");
Gurax_RealizeSymbolMark(Pow,				"**");
Gurax_RealizeSymbolMark(Quote,				"`");
Gurax_RealizeSymbolMark(Colon,				":");
Gurax_RealizeSymbolMark(ColonAfterSuffix,	":");
Gurax_RealizeSymbolMark(Period,				".");
Gurax_RealizeSymbolMark(ColonColon,			"::");
Gurax_RealizeSymbolMark(ColonAsterisk,		":*");
Gurax_RealizeSymbolMark(ColonAnd,			":&");
Gurax_RealizeSymbolMark(LParenthesis,		"(");
Gurax_RealizeSymbolMark(RParenthesis,		")");
Gurax_RealizeSymbolMark(LBrace,				"{");
Gurax_RealizeSymbolMark(RBrace,				"}");
Gurax_RealizeSymbolMark(LBlockParam,		"|");
Gurax_RealizeSymbolMark(RBlockParam,		"|");
Gurax_RealizeSymbolMark(LBracket,			"[");
Gurax_RealizeSymbolMark(RBracket,			"]");
Gurax_RealizeSymbolMark(Comma,				",");
Gurax_RealizeSymbolMark(Semicolon,			";");

}
