//==============================================================================
// Consts.cpp
//==============================================================================
#include "stdafx.h"

#define AssignConst(name) frame.Assign(#name, new Value_Number(name))

Gurax_BeginModuleScope(curl)

void AssignConsts(Frame& frame)
{
	// CURLcode
	AssignConst(CURLE_OK);
	AssignConst(CURLE_UNSUPPORTED_PROTOCOL);
	AssignConst(CURLE_FAILED_INIT);
	AssignConst(CURLE_URL_MALFORMAT);
	AssignConst(CURLE_NOT_BUILT_IN);
	AssignConst(CURLE_COULDNT_RESOLVE_PROXY);
	AssignConst(CURLE_COULDNT_RESOLVE_HOST);
	AssignConst(CURLE_COULDNT_CONNECT);
	AssignConst(CURLE_WEIRD_SERVER_REPLY);
	AssignConst(CURLE_REMOTE_ACCESS_DENIED);
	AssignConst(CURLE_FTP_ACCEPT_FAILED);
	AssignConst(CURLE_FTP_WEIRD_PASS_REPLY);
	AssignConst(CURLE_FTP_ACCEPT_TIMEOUT);
	AssignConst(CURLE_FTP_WEIRD_PASV_REPLY);
	AssignConst(CURLE_FTP_WEIRD_227_FORMAT);
	AssignConst(CURLE_FTP_CANT_GET_HOST);
	AssignConst(CURLE_HTTP2);
	AssignConst(CURLE_FTP_COULDNT_SET_TYPE);
	AssignConst(CURLE_PARTIAL_FILE);
	AssignConst(CURLE_FTP_COULDNT_RETR_FILE);
	AssignConst(CURLE_OBSOLETE20);
	AssignConst(CURLE_QUOTE_ERROR);
	AssignConst(CURLE_HTTP_RETURNED_ERROR);
	AssignConst(CURLE_WRITE_ERROR);
	AssignConst(CURLE_OBSOLETE24);
	AssignConst(CURLE_UPLOAD_FAILED);
	AssignConst(CURLE_READ_ERROR);
	AssignConst(CURLE_OUT_OF_MEMORY);
	AssignConst(CURLE_OPERATION_TIMEDOUT);
	AssignConst(CURLE_OBSOLETE29);
	AssignConst(CURLE_FTP_PORT_FAILED);
	AssignConst(CURLE_FTP_COULDNT_USE_REST);
	AssignConst(CURLE_OBSOLETE32);
	AssignConst(CURLE_RANGE_ERROR);
	AssignConst(CURLE_HTTP_POST_ERROR);
	AssignConst(CURLE_SSL_CONNECT_ERROR);
	AssignConst(CURLE_BAD_DOWNLOAD_RESUME);
	AssignConst(CURLE_FILE_COULDNT_READ_FILE);
	AssignConst(CURLE_LDAP_CANNOT_BIND);
	AssignConst(CURLE_LDAP_SEARCH_FAILED);
	AssignConst(CURLE_OBSOLETE40);
	AssignConst(CURLE_FUNCTION_NOT_FOUND);
	AssignConst(CURLE_ABORTED_BY_CALLBACK);
	AssignConst(CURLE_BAD_FUNCTION_ARGUMENT);
	AssignConst(CURLE_OBSOLETE44);
	AssignConst(CURLE_INTERFACE_FAILED);
	AssignConst(CURLE_OBSOLETE46);
	AssignConst(CURLE_TOO_MANY_REDIRECTS);
	AssignConst(CURLE_UNKNOWN_OPTION);
	AssignConst(CURLE_TELNET_OPTION_SYNTAX);
	AssignConst(CURLE_OBSOLETE50);
	AssignConst(CURLE_OBSOLETE51);
	AssignConst(CURLE_GOT_NOTHING);
	AssignConst(CURLE_SSL_ENGINE_NOTFOUND);
	AssignConst(CURLE_SSL_ENGINE_SETFAILED);
	AssignConst(CURLE_SEND_ERROR);
	AssignConst(CURLE_RECV_ERROR);
	AssignConst(CURLE_OBSOLETE57);
	AssignConst(CURLE_SSL_CERTPROBLEM);
	AssignConst(CURLE_SSL_CIPHER);
	AssignConst(CURLE_PEER_FAILED_VERIFICATION);
	AssignConst(CURLE_BAD_CONTENT_ENCODING);
	AssignConst(CURLE_LDAP_INVALID_URL);
	AssignConst(CURLE_FILESIZE_EXCEEDED);
	AssignConst(CURLE_USE_SSL_FAILED);
	AssignConst(CURLE_SEND_FAIL_REWIND);
	AssignConst(CURLE_SSL_ENGINE_INITFAILED);
	AssignConst(CURLE_LOGIN_DENIED);
	AssignConst(CURLE_TFTP_NOTFOUND);
	AssignConst(CURLE_TFTP_PERM);
	AssignConst(CURLE_REMOTE_DISK_FULL);
	AssignConst(CURLE_TFTP_ILLEGAL);
	AssignConst(CURLE_TFTP_UNKNOWNID);
	AssignConst(CURLE_REMOTE_FILE_EXISTS);
	AssignConst(CURLE_TFTP_NOSUCHUSER);
	AssignConst(CURLE_CONV_FAILED);
	AssignConst(CURLE_CONV_REQD);
	AssignConst(CURLE_SSL_CACERT_BADFILE);
	AssignConst(CURLE_REMOTE_FILE_NOT_FOUND);
	AssignConst(CURLE_SSH);
	AssignConst(CURLE_SSL_SHUTDOWN_FAILED);
	AssignConst(CURLE_AGAIN);
	AssignConst(CURLE_SSL_CRL_BADFILE);
	AssignConst(CURLE_SSL_ISSUER_ERROR);
	AssignConst(CURLE_FTP_PRET_FAILED);
	AssignConst(CURLE_RTSP_CSEQ_ERROR);
	AssignConst(CURLE_RTSP_SESSION_ERROR);
	AssignConst(CURLE_FTP_BAD_FILE_LIST);
	AssignConst(CURLE_CHUNK_FAILED);
	AssignConst(CURLE_NO_CONNECTION_AVAILABLE);
	AssignConst(CURLE_SSL_PINNEDPUBKEYNOTMATCH);
	AssignConst(CURLE_SSL_INVALIDCERTSTATUS);
	AssignConst(CURLE_HTTP2_STREAM);
	AssignConst(CURLE_RECURSIVE_API_CALL);
	AssignConst(CURLE_AUTH_ERROR);
	AssignConst(CURLE_HTTP3);
	AssignConst(CURLE_QUIC_CONNECT_ERROR);
	AssignConst(CURLE_PROXY);
	AssignConst(CURL_LAST);
	AssignConst(CURLE_OBSOLETE16);
	AssignConst(CURLE_OBSOLETE10);
	AssignConst(CURLE_OBSOLETE12);
	AssignConst(CURLE_FTP_WEIRD_SERVER_REPLY);
	AssignConst(CURLE_SSL_CACERT);
	AssignConst(CURLE_UNKNOWN_TELNET_OPTION);
	AssignConst(CURLE_SSL_PEER_CERTIFICATE);
	AssignConst(CURLE_OBSOLETE);
	AssignConst(CURLE_BAD_PASSWORD_ENTERED);
	AssignConst(CURLE_BAD_CALLING_ORDER);
	AssignConst(CURLE_FTP_USER_PASSWORD_INCORRECT);
	AssignConst(CURLE_FTP_CANT_RECONNECT);
	AssignConst(CURLE_FTP_COULDNT_GET_SIZE);
	AssignConst(CURLE_FTP_COULDNT_SET_ASCII);
	AssignConst(CURLE_FTP_WEIRD_USER_REPLY);
	AssignConst(CURLE_FTP_WRITE_ERROR);
	AssignConst(CURLE_LIBRARY_NOT_FOUND);
	AssignConst(CURLE_MALFORMAT_USER);
	AssignConst(CURLE_SHARE_IN_USE);
	AssignConst(CURLE_URL_MALFORMAT_USER);
	AssignConst(CURLE_FTP_ACCESS_DENIED);
	AssignConst(CURLE_FTP_COULDNT_SET_BINARY);
	AssignConst(CURLE_FTP_QUOTE_ERROR);
	AssignConst(CURLE_TFTP_DISKFULL);
	AssignConst(CURLE_TFTP_EXISTS);
	AssignConst(CURLE_HTTP_RANGE_ERROR);
	AssignConst(CURLE_FTP_SSL_FAILED);
	AssignConst(CURLE_OPERATION_TIMEOUTED);
	AssignConst(CURLE_HTTP_NOT_FOUND);
	AssignConst(CURLE_HTTP_PORT_FAILED);
	AssignConst(CURLE_FTP_COULDNT_STOR_FILE);
	AssignConst(CURLE_FTP_PARTIAL_FILE);
	AssignConst(CURLE_FTP_BAD_DOWNLOAD_RESUME);
	AssignConst(CURLE_ALREADY_COMPLETE);
	// CURLOPTTYPE	
	AssignConst(CURLOPTTYPE_LONG);
	AssignConst(CURLOPTTYPE_OBJECTPOINT);
	AssignConst(CURLOPTTYPE_FUNCTIONPOINT);
	AssignConst(CURLOPTTYPE_OFF_T);
	AssignConst(CURLOPTTYPE_BLOB);
	AssignConst(CURLOPTTYPE_STRINGPOINT);
	AssignConst(CURLOPTTYPE_SLISTPOINT);
	AssignConst(CURLOPTTYPE_CBPOINT);
	AssignConst(CURLOPTTYPE_VALUES);
	// CURLoption
	AssignConst(CURLOPT_WRITEDATA);
	AssignConst(CURLOPT_URL);
	AssignConst(CURLOPT_PORT);
	AssignConst(CURLOPT_PROXY);
	AssignConst(CURLOPT_USERPWD);
	AssignConst(CURLOPT_PROXYUSERPWD);
	AssignConst(CURLOPT_RANGE);
	AssignConst(CURLOPT_READDATA);
	AssignConst(CURLOPT_ERRORBUFFER);
	AssignConst(CURLOPT_WRITEFUNCTION);
	AssignConst(CURLOPT_READFUNCTION);
	AssignConst(CURLOPT_TIMEOUT);
	AssignConst(CURLOPT_INFILESIZE);
	AssignConst(CURLOPT_POSTFIELDS);
	AssignConst(CURLOPT_REFERER);
	AssignConst(CURLOPT_FTPPORT);
	AssignConst(CURLOPT_USERAGENT);
	AssignConst(CURLOPT_LOW_SPEED_LIMIT);
	AssignConst(CURLOPT_LOW_SPEED_TIME);
	AssignConst(CURLOPT_RESUME_FROM);
	AssignConst(CURLOPT_COOKIE);
	AssignConst(CURLOPT_HTTPHEADER);
	AssignConst(CURLOPT_HTTPPOST);
	AssignConst(CURLOPT_SSLCERT);
	AssignConst(CURLOPT_KEYPASSWD);
	AssignConst(CURLOPT_CRLF);
	AssignConst(CURLOPT_QUOTE);
	AssignConst(CURLOPT_HEADERDATA);
	AssignConst(CURLOPT_COOKIEFILE);
	AssignConst(CURLOPT_SSLVERSION);
	AssignConst(CURLOPT_TIMECONDITION);
	AssignConst(CURLOPT_TIMEVALUE);
	AssignConst(CURLOPT_CUSTOMREQUEST);
	AssignConst(CURLOPT_STDERR);
	AssignConst(CURLOPT_POSTQUOTE);
	AssignConst(CURLOPT_OBSOLETE40);
	AssignConst(CURLOPT_VERBOSE);
	AssignConst(CURLOPT_HEADER);
	AssignConst(CURLOPT_NOPROGRESS);
	AssignConst(CURLOPT_NOBODY);
	AssignConst(CURLOPT_FAILONERROR);
	AssignConst(CURLOPT_UPLOAD);
	AssignConst(CURLOPT_POST);
	AssignConst(CURLOPT_DIRLISTONLY);
	AssignConst(CURLOPT_APPEND);
	AssignConst(CURLOPT_NETRC);
	AssignConst(CURLOPT_FOLLOWLOCATION);
	AssignConst(CURLOPT_TRANSFERTEXT);
	AssignConst(CURLOPT_PUT);
	AssignConst(CURLOPT_PROGRESSFUNCTION);
	AssignConst(CURLOPT_XFERINFODATA);
	AssignConst(CURLOPT_AUTOREFERER);
	AssignConst(CURLOPT_PROXYPORT);
	AssignConst(CURLOPT_POSTFIELDSIZE);
	AssignConst(CURLOPT_HTTPPROXYTUNNEL);
	AssignConst(CURLOPT_INTERFACE);
	AssignConst(CURLOPT_KRBLEVEL);
	AssignConst(CURLOPT_SSL_VERIFYPEER);
	AssignConst(CURLOPT_CAINFO);
	AssignConst(CURLOPT_MAXREDIRS);
	AssignConst(CURLOPT_FILETIME);
	AssignConst(CURLOPT_TELNETOPTIONS);
	AssignConst(CURLOPT_MAXCONNECTS);
	AssignConst(CURLOPT_OBSOLETE72);
	AssignConst(CURLOPT_FRESH_CONNECT);
	AssignConst(CURLOPT_FORBID_REUSE);
	AssignConst(CURLOPT_RANDOM_FILE);
	AssignConst(CURLOPT_EGDSOCKET);
	AssignConst(CURLOPT_CONNECTTIMEOUT);
	AssignConst(CURLOPT_HEADERFUNCTION);
	AssignConst(CURLOPT_HTTPGET);
	AssignConst(CURLOPT_SSL_VERIFYHOST);
	AssignConst(CURLOPT_COOKIEJAR);
	AssignConst(CURLOPT_SSL_CIPHER_LIST);
	AssignConst(CURLOPT_HTTP_VERSION);
	AssignConst(CURLOPT_FTP_USE_EPSV);
	AssignConst(CURLOPT_SSLCERTTYPE);
	AssignConst(CURLOPT_SSLKEY);
	AssignConst(CURLOPT_SSLKEYTYPE);
	AssignConst(CURLOPT_SSLENGINE);
	AssignConst(CURLOPT_SSLENGINE_DEFAULT);
	AssignConst(CURLOPT_DNS_USE_GLOBAL_CACHE);
	AssignConst(CURLOPT_DNS_CACHE_TIMEOUT);
	AssignConst(CURLOPT_PREQUOTE);
	AssignConst(CURLOPT_DEBUGFUNCTION);
	AssignConst(CURLOPT_DEBUGDATA);
	AssignConst(CURLOPT_COOKIESESSION);
	AssignConst(CURLOPT_CAPATH);
	AssignConst(CURLOPT_BUFFERSIZE);
	AssignConst(CURLOPT_NOSIGNAL);
	AssignConst(CURLOPT_SHARE);
	AssignConst(CURLOPT_PROXYTYPE);
	AssignConst(CURLOPT_ACCEPT_ENCODING);
	AssignConst(CURLOPT_PRIVATE);
	AssignConst(CURLOPT_HTTP200ALIASES);
	AssignConst(CURLOPT_UNRESTRICTED_AUTH);
	AssignConst(CURLOPT_FTP_USE_EPRT);
	AssignConst(CURLOPT_HTTPAUTH);
	AssignConst(CURLOPT_SSL_CTX_FUNCTION);
	AssignConst(CURLOPT_SSL_CTX_DATA);
	AssignConst(CURLOPT_FTP_CREATE_MISSING_DIRS);
	AssignConst(CURLOPT_PROXYAUTH);
	AssignConst(CURLOPT_FTP_RESPONSE_TIMEOUT);
	AssignConst(CURLOPT_IPRESOLVE);
	AssignConst(CURLOPT_MAXFILESIZE);
	AssignConst(CURLOPT_INFILESIZE_LARGE);
	AssignConst(CURLOPT_RESUME_FROM_LARGE);
	AssignConst(CURLOPT_MAXFILESIZE_LARGE);
	AssignConst(CURLOPT_NETRC_FILE);
	AssignConst(CURLOPT_USE_SSL);
	AssignConst(CURLOPT_POSTFIELDSIZE_LARGE);
	AssignConst(CURLOPT_TCP_NODELAY);
	AssignConst(CURLOPT_FTPSSLAUTH);
	AssignConst(CURLOPT_IOCTLFUNCTION);
	AssignConst(CURLOPT_IOCTLDATA);
	AssignConst(CURLOPT_FTP_ACCOUNT);
	AssignConst(CURLOPT_COOKIELIST);
	AssignConst(CURLOPT_IGNORE_CONTENT_LENGTH);
	AssignConst(CURLOPT_FTP_SKIP_PASV_IP);
	AssignConst(CURLOPT_FTP_FILEMETHOD);
	AssignConst(CURLOPT_LOCALPORT);
	AssignConst(CURLOPT_LOCALPORTRANGE);
	AssignConst(CURLOPT_CONNECT_ONLY);
	AssignConst(CURLOPT_CONV_FROM_NETWORK_FUNCTION);
	AssignConst(CURLOPT_CONV_TO_NETWORK_FUNCTION);
	AssignConst(CURLOPT_CONV_FROM_UTF8_FUNCTION);
	AssignConst(CURLOPT_MAX_SEND_SPEED_LARGE);
	AssignConst(CURLOPT_MAX_RECV_SPEED_LARGE);
	AssignConst(CURLOPT_FTP_ALTERNATIVE_TO_USER);
	AssignConst(CURLOPT_SOCKOPTFUNCTION);
	AssignConst(CURLOPT_SOCKOPTDATA);
	AssignConst(CURLOPT_SSL_SESSIONID_CACHE);
	AssignConst(CURLOPT_SSH_AUTH_TYPES);
	AssignConst(CURLOPT_SSH_PUBLIC_KEYFILE);
	AssignConst(CURLOPT_SSH_PRIVATE_KEYFILE);
	AssignConst(CURLOPT_FTP_SSL_CCC);
	AssignConst(CURLOPT_TIMEOUT_MS);
	AssignConst(CURLOPT_CONNECTTIMEOUT_MS);
	AssignConst(CURLOPT_HTTP_TRANSFER_DECODING);
	AssignConst(CURLOPT_HTTP_CONTENT_DECODING);
	AssignConst(CURLOPT_NEW_FILE_PERMS);
	AssignConst(CURLOPT_NEW_DIRECTORY_PERMS);
	AssignConst(CURLOPT_POSTREDIR);
	AssignConst(CURLOPT_SSH_HOST_PUBLIC_KEY_MD5);
	AssignConst(CURLOPT_OPENSOCKETFUNCTION);
	AssignConst(CURLOPT_OPENSOCKETDATA);
	AssignConst(CURLOPT_COPYPOSTFIELDS);
	AssignConst(CURLOPT_PROXY_TRANSFER_MODE);
	AssignConst(CURLOPT_SEEKFUNCTION);
	AssignConst(CURLOPT_SEEKDATA);
	AssignConst(CURLOPT_CRLFILE);
	AssignConst(CURLOPT_ISSUERCERT);
	AssignConst(CURLOPT_ADDRESS_SCOPE);
	AssignConst(CURLOPT_CERTINFO);
	AssignConst(CURLOPT_USERNAME);
	AssignConst(CURLOPT_PASSWORD);
	AssignConst(CURLOPT_PROXYUSERNAME);
	AssignConst(CURLOPT_PROXYPASSWORD);
	AssignConst(CURLOPT_NOPROXY);
	AssignConst(CURLOPT_TFTP_BLKSIZE);
	AssignConst(CURLOPT_SOCKS5_GSSAPI_SERVICE);
	AssignConst(CURLOPT_SOCKS5_GSSAPI_NEC);
	AssignConst(CURLOPT_PROTOCOLS);
	AssignConst(CURLOPT_REDIR_PROTOCOLS);
	AssignConst(CURLOPT_SSH_KNOWNHOSTS);
	AssignConst(CURLOPT_SSH_KEYFUNCTION);
	AssignConst(CURLOPT_SSH_KEYDATA);
	AssignConst(CURLOPT_MAIL_FROM);
	AssignConst(CURLOPT_MAIL_RCPT);
	AssignConst(CURLOPT_FTP_USE_PRET);
	AssignConst(CURLOPT_RTSP_REQUEST);
	AssignConst(CURLOPT_RTSP_SESSION_ID);
	AssignConst(CURLOPT_RTSP_STREAM_URI);
	AssignConst(CURLOPT_RTSP_TRANSPORT);
	AssignConst(CURLOPT_RTSP_CLIENT_CSEQ);
	AssignConst(CURLOPT_RTSP_SERVER_CSEQ);
	AssignConst(CURLOPT_INTERLEAVEDATA);
	AssignConst(CURLOPT_INTERLEAVEFUNCTION);
	AssignConst(CURLOPT_WILDCARDMATCH);
	AssignConst(CURLOPT_CHUNK_BGN_FUNCTION);
	AssignConst(CURLOPT_CHUNK_END_FUNCTION);
	AssignConst(CURLOPT_FNMATCH_FUNCTION);
	AssignConst(CURLOPT_CHUNK_DATA);
	AssignConst(CURLOPT_FNMATCH_DATA);
	AssignConst(CURLOPT_RESOLVE);
	AssignConst(CURLOPT_TLSAUTH_USERNAME);
	AssignConst(CURLOPT_TLSAUTH_PASSWORD);
	AssignConst(CURLOPT_TLSAUTH_TYPE);
	AssignConst(CURLOPT_TRANSFER_ENCODING);
	AssignConst(CURLOPT_CLOSESOCKETFUNCTION);
	AssignConst(CURLOPT_CLOSESOCKETDATA);
	AssignConst(CURLOPT_GSSAPI_DELEGATION);
	AssignConst(CURLOPT_DNS_SERVERS);
	AssignConst(CURLOPT_ACCEPTTIMEOUT_MS);
	AssignConst(CURLOPT_TCP_KEEPALIVE);
	AssignConst(CURLOPT_TCP_KEEPIDLE);
	AssignConst(CURLOPT_TCP_KEEPINTVL);
	AssignConst(CURLOPT_SSL_OPTIONS);
	AssignConst(CURLOPT_MAIL_AUTH);
	AssignConst(CURLOPT_SASL_IR);
	AssignConst(CURLOPT_XFERINFOFUNCTION);
	AssignConst(CURLOPT_XOAUTH2_BEARER);
	AssignConst(CURLOPT_DNS_INTERFACE);
	AssignConst(CURLOPT_DNS_LOCAL_IP4);
	AssignConst(CURLOPT_DNS_LOCAL_IP6);
	AssignConst(CURLOPT_LOGIN_OPTIONS);
	AssignConst(CURLOPT_SSL_ENABLE_NPN);
	AssignConst(CURLOPT_SSL_ENABLE_ALPN);
	AssignConst(CURLOPT_EXPECT_100_TIMEOUT_MS);
	AssignConst(CURLOPT_PROXYHEADER);
	AssignConst(CURLOPT_HEADEROPT);
	AssignConst(CURLOPT_PINNEDPUBLICKEY);
	AssignConst(CURLOPT_UNIX_SOCKET_PATH);
	AssignConst(CURLOPT_SSL_VERIFYSTATUS);
	AssignConst(CURLOPT_SSL_FALSESTART);
	AssignConst(CURLOPT_PATH_AS_IS);
	AssignConst(CURLOPT_PROXY_SERVICE_NAME);
	AssignConst(CURLOPT_SERVICE_NAME);
	AssignConst(CURLOPT_PIPEWAIT);
	AssignConst(CURLOPT_DEFAULT_PROTOCOL);
	AssignConst(CURLOPT_STREAM_WEIGHT);
	AssignConst(CURLOPT_STREAM_DEPENDS);
	AssignConst(CURLOPT_STREAM_DEPENDS_E);
	AssignConst(CURLOPT_TFTP_NO_OPTIONS);
	AssignConst(CURLOPT_CONNECT_TO);
	AssignConst(CURLOPT_TCP_FASTOPEN);
	AssignConst(CURLOPT_KEEP_SENDING_ON_ERROR);
	AssignConst(CURLOPT_PROXY_CAINFO);
	AssignConst(CURLOPT_PROXY_CAPATH);
	AssignConst(CURLOPT_PROXY_SSL_VERIFYPEER);
	AssignConst(CURLOPT_PROXY_SSL_VERIFYHOST);
	AssignConst(CURLOPT_PROXY_SSLVERSION);
	AssignConst(CURLOPT_PROXY_TLSAUTH_USERNAME);
	AssignConst(CURLOPT_PROXY_TLSAUTH_PASSWORD);
	AssignConst(CURLOPT_PROXY_TLSAUTH_TYPE);
	AssignConst(CURLOPT_PROXY_SSLCERT);
	AssignConst(CURLOPT_PROXY_SSLCERTTYPE);
	AssignConst(CURLOPT_PROXY_SSLKEY);
	AssignConst(CURLOPT_PROXY_SSLKEYTYPE);
	AssignConst(CURLOPT_PROXY_KEYPASSWD);
	AssignConst(CURLOPT_PROXY_SSL_CIPHER_LIST);
	AssignConst(CURLOPT_PROXY_CRLFILE);
	AssignConst(CURLOPT_PROXY_SSL_OPTIONS);
	AssignConst(CURLOPT_PRE_PROXY);
	AssignConst(CURLOPT_PROXY_PINNEDPUBLICKEY);
	AssignConst(CURLOPT_ABSTRACT_UNIX_SOCKET);
	AssignConst(CURLOPT_SUPPRESS_CONNECT_HEADERS);
	AssignConst(CURLOPT_REQUEST_TARGET);
	AssignConst(CURLOPT_SOCKS5_AUTH);
	AssignConst(CURLOPT_SSH_COMPRESSION);
	AssignConst(CURLOPT_MIMEPOST);
	AssignConst(CURLOPT_TIMEVALUE_LARGE);
	AssignConst(CURLOPT_HAPPY_EYEBALLS_TIMEOUT_MS);
	AssignConst(CURLOPT_RESOLVER_START_FUNCTION);
	AssignConst(CURLOPT_RESOLVER_START_DATA);
	AssignConst(CURLOPT_HAPROXYPROTOCOL);
	AssignConst(CURLOPT_DNS_SHUFFLE_ADDRESSES);
	AssignConst(CURLOPT_TLS13_CIPHERS);
	AssignConst(CURLOPT_PROXY_TLS13_CIPHERS);
	AssignConst(CURLOPT_DISALLOW_USERNAME_IN_URL);
	AssignConst(CURLOPT_DOH_URL);
	AssignConst(CURLOPT_UPLOAD_BUFFERSIZE);
	AssignConst(CURLOPT_UPKEEP_INTERVAL_MS);
	AssignConst(CURLOPT_CURLU);
	AssignConst(CURLOPT_TRAILERFUNCTION);
	AssignConst(CURLOPT_TRAILERDATA);
	AssignConst(CURLOPT_HTTP09_ALLOWED);
	AssignConst(CURLOPT_ALTSVC_CTRL);
	AssignConst(CURLOPT_ALTSVC);
	AssignConst(CURLOPT_MAXAGE_CONN);
	AssignConst(CURLOPT_SASL_AUTHZID);
	AssignConst(CURLOPT_MAIL_RCPT_ALLLOWFAILS);
	AssignConst(CURLOPT_SSLCERT_BLOB);
	AssignConst(CURLOPT_SSLKEY_BLOB);
	AssignConst(CURLOPT_PROXY_SSLCERT_BLOB);
	AssignConst(CURLOPT_PROXY_SSLKEY_BLOB);
	AssignConst(CURLOPT_ISSUERCERT_BLOB);
	AssignConst(CURLOPT_PROXY_ISSUERCERT);
	AssignConst(CURLOPT_PROXY_ISSUERCERT_BLOB);
	AssignConst(CURLOPT_SSL_EC_CURVES);
	AssignConst(CURLOPT_LASTENTRY);
	AssignConst(CURLOPT_ENCODING);
	AssignConst(CURLOPT_FILE);
	AssignConst(CURLOPT_INFILE);
	AssignConst(CURLOPT_WRITEHEADER);
	AssignConst(CURLOPT_WRITEINFO);
	AssignConst(CURLOPT_CLOSEPOLICY);
	AssignConst(CURLOPT_PROGRESSDATA);
	AssignConst(CURLOPT_SERVER_RESPONSE_TIMEOUT);
	AssignConst(CURLOPT_POST301);
	AssignConst(CURLOPT_SSLKEYPASSWD);
	AssignConst(CURLOPT_FTPAPPEND);
	AssignConst(CURLOPT_FTPLISTONLY);
	AssignConst(CURLOPT_FTP_SSL);
	AssignConst(CURLOPT_SSLCERTPASSWD);
	AssignConst(CURLOPT_KRB4LEVEL);
	AssignConst(CURLOPT_RTSPHEADER);
	// CURLINFO
	AssignConst(CURLINFO_STRING);
	AssignConst(CURLINFO_LONG);
	AssignConst(CURLINFO_DOUBLE);
	AssignConst(CURLINFO_SLIST);
	AssignConst(CURLINFO_PTR);
	AssignConst(CURLINFO_SOCKET);
	AssignConst(CURLINFO_OFF_T);
	AssignConst(CURLINFO_MASK);
	AssignConst(CURLINFO_TYPEMASK);
	AssignConst(CURLINFO_NONE);
	AssignConst(CURLINFO_EFFECTIVE_URL);
	AssignConst(CURLINFO_RESPONSE_CODE);
	AssignConst(CURLINFO_TOTAL_TIME);
	AssignConst(CURLINFO_NAMELOOKUP_TIME);
	AssignConst(CURLINFO_CONNECT_TIME);
	AssignConst(CURLINFO_PRETRANSFER_TIME);
	AssignConst(CURLINFO_SIZE_UPLOAD);
	AssignConst(CURLINFO_SIZE_UPLOAD_T);
	AssignConst(CURLINFO_SIZE_DOWNLOAD);
	AssignConst(CURLINFO_SIZE_DOWNLOAD_T);
	AssignConst(CURLINFO_SPEED_DOWNLOAD);
	AssignConst(CURLINFO_SPEED_DOWNLOAD_T);
	AssignConst(CURLINFO_SPEED_UPLOAD);
	AssignConst(CURLINFO_SPEED_UPLOAD_T);
	AssignConst(CURLINFO_HEADER_SIZE);
	AssignConst(CURLINFO_REQUEST_SIZE);
	AssignConst(CURLINFO_SSL_VERIFYRESULT);
	AssignConst(CURLINFO_FILETIME);
	AssignConst(CURLINFO_FILETIME_T);
	AssignConst(CURLINFO_CONTENT_LENGTH_DOWNLOAD);
	AssignConst(CURLINFO_CONTENT_LENGTH_DOWNLOAD_T);
	AssignConst(CURLINFO_CONTENT_LENGTH_UPLOAD);
	AssignConst(CURLINFO_CONTENT_LENGTH_UPLOAD_T);
	AssignConst(CURLINFO_STARTTRANSFER_TIME);
	AssignConst(CURLINFO_CONTENT_TYPE);
	AssignConst(CURLINFO_REDIRECT_TIME);
	AssignConst(CURLINFO_REDIRECT_COUNT);
	AssignConst(CURLINFO_PRIVATE);
	AssignConst(CURLINFO_HTTP_CONNECTCODE);
	AssignConst(CURLINFO_HTTPAUTH_AVAIL);
	AssignConst(CURLINFO_PROXYAUTH_AVAIL);
	AssignConst(CURLINFO_OS_ERRNO);
	AssignConst(CURLINFO_NUM_CONNECTS);
	AssignConst(CURLINFO_SSL_ENGINES);
	AssignConst(CURLINFO_COOKIELIST);
	AssignConst(CURLINFO_LASTSOCKET);
	AssignConst(CURLINFO_FTP_ENTRY_PATH);
	AssignConst(CURLINFO_REDIRECT_URL);
	AssignConst(CURLINFO_PRIMARY_IP);
	AssignConst(CURLINFO_APPCONNECT_TIME);
	AssignConst(CURLINFO_CERTINFO);
	AssignConst(CURLINFO_CONDITION_UNMET);
	AssignConst(CURLINFO_RTSP_SESSION_ID);
	AssignConst(CURLINFO_RTSP_CLIENT_CSEQ);
	AssignConst(CURLINFO_RTSP_SERVER_CSEQ);
	AssignConst(CURLINFO_RTSP_CSEQ_RECV);
	AssignConst(CURLINFO_PRIMARY_PORT);
	AssignConst(CURLINFO_LOCAL_IP);
	AssignConst(CURLINFO_LOCAL_PORT);
	AssignConst(CURLINFO_TLS_SESSION);
	AssignConst(CURLINFO_ACTIVESOCKET);
	AssignConst(CURLINFO_TLS_SSL_PTR);
	AssignConst(CURLINFO_HTTP_VERSION);
	AssignConst(CURLINFO_PROXY_SSL_VERIFYRESULT);
	AssignConst(CURLINFO_PROTOCOL);
	AssignConst(CURLINFO_SCHEME);
	AssignConst(CURLINFO_TOTAL_TIME_T);
	AssignConst(CURLINFO_NAMELOOKUP_TIME_T);
	AssignConst(CURLINFO_CONNECT_TIME_T);
	AssignConst(CURLINFO_PRETRANSFER_TIME_T);
	AssignConst(CURLINFO_STARTTRANSFER_TIME_T);
	AssignConst(CURLINFO_REDIRECT_TIME_T);
	AssignConst(CURLINFO_APPCONNECT_TIME_T);
	AssignConst(CURLINFO_RETRY_AFTER);
	AssignConst(CURLINFO_EFFECTIVE_METHOD);
	AssignConst(CURLINFO_PROXY_ERROR);
	AssignConst(CURLINFO_LASTONE);
	AssignConst(CURLINFO_HTTP_CODE);
	// curl_closepolicy
	AssignConst(CURLCLOSEPOLICY_NONE);
	AssignConst(CURLCLOSEPOLICY_OLDEST);
	AssignConst(CURLCLOSEPOLICY_LEAST_RECENTLY_USED);
	AssignConst(CURLCLOSEPOLICY_LEAST_TRAFFIC);
	AssignConst(CURLCLOSEPOLICY_SLOWEST);
	AssignConst(CURLCLOSEPOLICY_CALLBACK);
	AssignConst(CURLCLOSEPOLICY_LAST);
	// curl_sslbackend;
  CURLSSLBACKEND_NONE = 0,
  CURLSSLBACKEND_OPENSSL = 1,
  CURLSSLBACKEND_GNUTLS = 2,
  CURLSSLBACKEND_NSS = 3,
  CURLSSLBACKEND_OBSOLETE4 = 4,  /* Was QSOSSL. */
  CURLSSLBACKEND_GSKIT = 5,
  CURLSSLBACKEND_POLARSSL = 6,
  CURLSSLBACKEND_WOLFSSL = 7,
  CURLSSLBACKEND_SCHANNEL = 8,
  CURLSSLBACKEND_SECURETRANSPORT = 9,
  CURLSSLBACKEND_AXTLS = 10, /* never used since 7.63.0 */
  CURLSSLBACKEND_MBEDTLS = 11,
  CURLSSLBACKEND_MESALINK = 12,
  CURLSSLBACKEND_BEARSSL = 13

	// curlfiletype
  CURLFILETYPE_FILE = 0,
  CURLFILETYPE_DIRECTORY,
  CURLFILETYPE_SYMLINK,
  CURLFILETYPE_DEVICE_BLOCK,
  CURLFILETYPE_DEVICE_CHAR,
  CURLFILETYPE_NAMEDPIPE,
  CURLFILETYPE_SOCKET,
  CURLFILETYPE_DOOR, /* is possible only on Sun Solaris now */
  CURLFILETYPE_UNKNOWN /* should never occur */

	// curlsocktype
  CURLSOCKTYPE_IPCXN,  /* socket created for a specific IP connection */
  CURLSOCKTYPE_ACCEPT, /* socket created by accept() call */
  CURLSOCKTYPE_LAST    /* never use */

	// curlioerr
  CURLIOE_OK,            /* I/O operation successful */
  CURLIOE_UNKNOWNCMD,    /* command was unknown to callback */
  CURLIOE_FAILRESTART,   /* failed to restart the read */
  CURLIOE_LAST           /* never use */

	// curliocmd	
  CURLIOCMD_NOP,         /* no operation */
  CURLIOCMD_RESTARTREAD, /* restart the read stream from start */
  CURLIOCMD_LAST         /* never use */

	// curlinfotype
  CURLINFO_TEXT = 0,
  CURLINFO_HEADER_IN,    /* 1 */
  CURLINFO_HEADER_OUT,   /* 2 */
  CURLINFO_DATA_IN,      /* 3 */
  CURLINFO_DATA_OUT,     /* 4 */
  CURLINFO_SSL_DATA_IN,  /* 5 */
  CURLINFO_SSL_DATA_OUT, /* 6 */
  CURLINFO_END

	// CURLproxycode
  CURLPX_OK,
  CURLPX_BAD_ADDRESS_TYPE,
  CURLPX_BAD_VERSION,
  CURLPX_CLOSED,
  CURLPX_GSSAPI,
  CURLPX_GSSAPI_PERMSG,
  CURLPX_GSSAPI_PROTECTION,
  CURLPX_IDENTD,
  CURLPX_IDENTD_DIFFER,
  CURLPX_LONG_HOSTNAME,
  CURLPX_LONG_PASSWD,
  CURLPX_LONG_USER,
  CURLPX_NO_AUTH,
  CURLPX_RECV_ADDRESS,
  CURLPX_RECV_AUTH,
  CURLPX_RECV_CONNECT,
  CURLPX_RECV_REQACK,
  CURLPX_REPLY_ADDRESS_TYPE_NOT_SUPPORTED,
  CURLPX_REPLY_COMMAND_NOT_SUPPORTED,
  CURLPX_REPLY_CONNECTION_REFUSED,
  CURLPX_REPLY_GENERAL_SERVER_FAILURE,
  CURLPX_REPLY_HOST_UNREACHABLE,
  CURLPX_REPLY_NETWORK_UNREACHABLE,
  CURLPX_REPLY_NOT_ALLOWED,
  CURLPX_REPLY_TTL_EXPIRED,
  CURLPX_REPLY_UNASSIGNED,
  CURLPX_REQUEST_FAILED,
  CURLPX_RESOLVE_HOST,
  CURLPX_SEND_AUTH,
  CURLPX_SEND_CONNECT,
  CURLPX_SEND_REQUEST,
  CURLPX_UNKNOWN_FAIL,
  CURLPX_UNKNOWN_MODE,
  CURLPX_USER_REJECTED,
  CURLPX_LAST /* never use */

	// curl_proxytype
  CURLPROXY_HTTP = 0,   /* added in 7.10, new in 7.19.4 default is to use
                           CONNECT HTTP/1.1 */
  CURLPROXY_HTTP_1_0 = 1,   /* added in 7.19.4, force to use CONNECT
                               HTTP/1.0  */
  CURLPROXY_HTTPS = 2, /* added in 7.52.0 */
  CURLPROXY_SOCKS4 = 4, /* support added in 7.15.2, enum existed already
                           in 7.10 */
  CURLPROXY_SOCKS5 = 5, /* added in 7.10 */
  CURLPROXY_SOCKS4A = 6, /* added in 7.18.0 */
  CURLPROXY_SOCKS5_HOSTNAME = 7 /* Use the SOCKS5 protocol but pass along the

	// curl_usesssl
  CURLUSESSL_NONE,    /* do not attempt to use SSL */
  CURLUSESSL_TRY,     /* try using SSL, proceed anyway otherwise */
  CURLUSESSL_CONTROL, /* SSL for the control connection or fail */
  CURLUSESSL_ALL,     /* SSL for all communication or fail */
  CURLUSESSL_LAST     /* not an option, never use */

	// curl_ftpccc
  CURLFTPSSL_CCC_NONE,    /* do not send CCC */
  CURLFTPSSL_CCC_PASSIVE, /* Let the server initiate the shutdown */
  CURLFTPSSL_CCC_ACTIVE,  /* Initiate the shutdown */
  CURLFTPSSL_CCC_LAST     /* not an option, never use */

	// curl_ftpauth
  CURLFTPAUTH_DEFAULT, /* let libcurl decide */
  CURLFTPAUTH_SSL,     /* use "AUTH SSL" */
  CURLFTPAUTH_TLS,     /* use "AUTH TLS" */
  CURLFTPAUTH_LAST /* not an option, never use */

	// curl_ftpcreatedir
  CURLFTP_CREATE_DIR_NONE,  /* do NOT create missing dirs! */
  CURLFTP_CREATE_DIR,       /* (FTP/SFTP) if CWD fails, try MKD and then CWD
                               again if MKD succeeded, for SFTP this does
                               similar magic */
  CURLFTP_CREATE_DIR_RETRY, /* (FTP only) if CWD fails, try MKD and then CWD
                               again even if MKD failed! */
  CURLFTP_CREATE_DIR_LAST   /* not an option, never use */

	// curl_ftpmethod
  CURLFTPMETHOD_DEFAULT,   /* let libcurl pick */
  CURLFTPMETHOD_MULTICWD,  /* single CWD operation for each path part */
  CURLFTPMETHOD_NOCWD,     /* no CWD at all */
  CURLFTPMETHOD_SINGLECWD, /* one CWD to full dir, then work on file */
  CURLFTPMETHOD_LAST       /* not an option, never use */

	// CURLOPT_HTTP_VERSION
  CURL_HTTP_VERSION_NONE, /* setting this means we don't care, and that we'd
                             like the library to choose the best possible
                             for us! */
  CURL_HTTP_VERSION_1_0,  /* please use HTTP 1.0 in the request */
  CURL_HTTP_VERSION_1_1,  /* please use HTTP 1.1 in the request */
  CURL_HTTP_VERSION_2_0,  /* please use HTTP 2 in the request */
  CURL_HTTP_VERSION_2TLS, /* use version 2 for HTTPS, version 1.1 for HTTP */
  CURL_HTTP_VERSION_2_PRIOR_KNOWLEDGE,  /* please use HTTP 2 without HTTP/1.1
                                           Upgrade */
  CURL_HTTP_VERSION_3 = 30, /* Makes use of explicit HTTP/3 without fallback.
                               Use CURLOPT_ALTSVC to enable HTTP/3 upgrade */
  CURL_HTTP_VERSION_LAST /* *ILLEGAL* http version */

	// RTSP requests
    CURL_RTSPREQ_NONE, /* first in list */
    CURL_RTSPREQ_OPTIONS,
    CURL_RTSPREQ_DESCRIBE,
    CURL_RTSPREQ_ANNOUNCE,
    CURL_RTSPREQ_SETUP,
    CURL_RTSPREQ_PLAY,
    CURL_RTSPREQ_PAUSE,
    CURL_RTSPREQ_TEARDOWN,
    CURL_RTSPREQ_GET_PARAMETER,
    CURL_RTSPREQ_SET_PARAMETER,
    CURL_RTSPREQ_RECORD,
    CURL_RTSPREQ_RECEIVE,
    CURL_RTSPREQ_LAST /* last in list */

	// CURL_NETRC_OPTION
  CURL_NETRC_IGNORED,     /* The .netrc will never be read.
  CURL_NETRC_OPTIONAL,    /* A user:password in the URL will be preferred
  CURL_NETRC_REQUIRED,    /* A user:password in the URL will be ignored.
  CURL_NETRC_LAST

	// CURL_SSLVERSION
  CURL_SSLVERSION_DEFAULT,
  CURL_SSLVERSION_TLSv1, /* TLS 1.x */
  CURL_SSLVERSION_SSLv2,
  CURL_SSLVERSION_SSLv3,
  CURL_SSLVERSION_TLSv1_0,
  CURL_SSLVERSION_TLSv1_1,
  CURL_SSLVERSION_TLSv1_2,
  CURL_SSLVERSION_TLSv1_3,

  CURL_SSLVERSION_LAST /* never use, keep last */

	// CURL_SSLVERSION_MAX
  CURL_SSLVERSION_MAX_NONE =     0,
  CURL_SSLVERSION_MAX_DEFAULT =  (CURL_SSLVERSION_TLSv1   << 16),
  CURL_SSLVERSION_MAX_TLSv1_0 =  (CURL_SSLVERSION_TLSv1_0 << 16),
  CURL_SSLVERSION_MAX_TLSv1_1 =  (CURL_SSLVERSION_TLSv1_1 << 16),
  CURL_SSLVERSION_MAX_TLSv1_2 =  (CURL_SSLVERSION_TLSv1_2 << 16),
  CURL_SSLVERSION_MAX_TLSv1_3 =  (CURL_SSLVERSION_TLSv1_3 << 16),

  /* never use, keep last */
  CURL_SSLVERSION_MAX_LAST =     (CURL_SSLVERSION_LAST    << 16)

	// CURL_TLSAUTH
  CURL_TLSAUTH_NONE,
  CURL_TLSAUTH_SRP,
  CURL_TLSAUTH_LAST /* never use, keep last */

	// curl_TimeCond
  CURL_TIMECOND_NONE,

  CURL_TIMECOND_IFMODSINCE,
  CURL_TIMECOND_IFUNMODSINCE,
  CURL_TIMECOND_LASTMOD,

  CURL_TIMECOND_LAST

	// CURLformoption
  CURLFORM_NOTHING,        /********* the first one is unused ************/
  CURLFORM_COPYNAME,
  CURLFORM_PTRNAME,
  CURLFORM_NAMELENGTH,
  CURLFORM_COPYCONTENTS,
  CURLFORM_PTRCONTENTS,
  CURLFORM_CONTENTSLENGTH,
  CURLFORM_FILECONTENT,
  CURLFORM_ARRAY,
  CURLFORM_OBSOLETE,
  CURLFORM_FILE,

  CURLFORM_BUFFER,
  CURLFORM_BUFFERPTR,
  CURLFORM_BUFFERLENGTH,

  CURLFORM_CONTENTTYPE,
  CURLFORM_CONTENTHEADER,
  CURLFORM_FILENAME,
  CURLFORM_END,
  CURLFORM_OBSOLETE2,

  CURLFORM_STREAM,
  CURLFORM_CONTENTLEN, /* added in 7.46.0, provide a curl_off_t length */

  CURLFORM_LASTENTRY /* the last unused */

	// CURLFORMCode
  CURL_FORMADD_OK, /* first, no error */

  CURL_FORMADD_MEMORY,
  CURL_FORMADD_OPTION_TWICE,
  CURL_FORMADD_NULL,
  CURL_FORMADD_UNKNOWN_OPTION,
  CURL_FORMADD_INCOMPLETE,
  CURL_FORMADD_ILLEGAL_ARRAY,
  CURL_FORMADD_DISABLED, /* libcurl was built with this disabled */

  CURL_FORMADD_LAST /* last */

	// CURLsslset
  CURLSSLSET_OK = 0,
  CURLSSLSET_UNKNOWN_BACKEND,
  CURLSSLSET_TOO_LATE,
  CURLSSLSET_NO_BACKENDS /* libcurl was built without any SSL support */

	// curl_closepolicy
  CURLCLOSEPOLICY_NONE, /* first, never use this */

  CURLCLOSEPOLICY_OLDEST,
  CURLCLOSEPOLICY_LEAST_RECENTLY_USED,
  CURLCLOSEPOLICY_LEAST_TRAFFIC,
  CURLCLOSEPOLICY_SLOWEST,
  CURLCLOSEPOLICY_CALLBACK,

  CURLCLOSEPOLICY_LAST /* last, never use this */

	// curl_lock_data
  CURL_LOCK_DATA_NONE = 0,
  /*  CURL_LOCK_DATA_SHARE is used internally to say that
   *  the locking is just made to change the internal state of the share
   *  itself.
   */
  CURL_LOCK_DATA_SHARE,
  CURL_LOCK_DATA_COOKIE,
  CURL_LOCK_DATA_DNS,
  CURL_LOCK_DATA_SSL_SESSION,
  CURL_LOCK_DATA_CONNECT,
  CURL_LOCK_DATA_PSL,
  CURL_LOCK_DATA_LAST
	// curl_lock_accesss
  CURL_LOCK_ACCESS_NONE = 0,   /* unspecified action */
  CURL_LOCK_ACCESS_SHARED = 1, /* for read perhaps */
  CURL_LOCK_ACCESS_SINGLE = 2, /* for write perhaps */
  CURL_LOCK_ACCESS_LAST        /* never use */

	// CURLSHcode
  CURLSHE_OK,  /* all is fine */
  CURLSHE_BAD_OPTION, /* 1 */
  CURLSHE_IN_USE,     /* 2 */
  CURLSHE_INVALID,    /* 3 */
  CURLSHE_NOMEM,      /* 4 out of memory */
  CURLSHE_NOT_BUILT_IN, /* 5 feature not present in lib */
  CURLSHE_LAST        /* never use */

	// CURLSHoption
  CURLSHOPT_NONE,  /* don't use */
  CURLSHOPT_SHARE,   /* specify a data type to share */
  CURLSHOPT_UNSHARE, /* specify which data type to stop sharing */
  CURLSHOPT_LOCKFUNC,   /* pass in a 'curl_lock_function' pointer */
  CURLSHOPT_UNLOCKFUNC, /* pass in a 'curl_unlock_function' pointer */
  CURLSHOPT_USERDATA,   /* pass in a user data pointer used in the lock/unlock
                           callback functions */
  CURLSHOPT_LAST  /* never use */

	// CURLversion
  CURLVERSION_FIRST,
  CURLVERSION_SECOND,
  CURLVERSION_THIRD,
  CURLVERSION_FOURTH,
  CURLVERSION_FIFTH,
  CURLVERSION_SIXTH,
  CURLVERSION_SEVENTH,
  CURLVERSION_EIGHTH,
  CURLVERSION_LAST /* never actually use this */
}



Gurax_EndModuleScope(curl)
