//==============================================================================
// VType_wxPrintDC.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXPRINTDC_H
#define GURAX_MODULE_WX_VTYPE_WXPRINTDC_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/dcprint.h>
#include "Util.h"
#include "VType_wxDC.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxPrintDC
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxPrintDC : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxPrintDC VTYPE_wxPrintDC;

//------------------------------------------------------------------------------
// Value_wxPrintDC
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxPrintDC : public Value_wxDC {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxPrintDC);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxPrintDC");
protected:
	wxPrintDC& _entity;
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxPrintDC() = delete;
	explicit Value_wxPrintDC(const wxPrintDC& entity, VType& vtype = VTYPE_wxPrintDC) :
		Value_wxDC(entity, vtype), _entity(const_cast<wxPrintDC&>(entity)) {}
	// Copy constructor/operator
	Value_wxPrintDC(const Value_wxPrintDC& src) = delete;
	Value_wxPrintDC& operator=(const Value_wxPrintDC& src) = delete;
	// Move constructor/operator
	Value_wxPrintDC(Value_wxPrintDC&& src) noexcept = delete;
	Value_wxPrintDC& operator=(Value_wxPrintDC&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxPrintDC() = default;
public:
	wxPrintDC& GetEntity() { return _entity; }
	const wxPrintDC& GetEntity() const { return _entity; }
	wxPrintDC* GetEntityPtr() { return &_entity; }
	const wxPrintDC* GetEntityPtr() const { return &_entity; }
public:
	static wxPrintDC& GetEntity(Value& value) {
		return dynamic_cast<Value_wxPrintDC&>(value).GetEntity();
	}
	static const wxPrintDC& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxPrintDC&>(value).GetEntity();
	}
	static wxPrintDC* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxPrintDC&>(value).GetEntityPtr();
	}
	static const wxPrintDC* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxPrintDC&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
