//==============================================================================
// VType_wxGraphicsPen.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"""(
# Overview

# Predefined Variable

${help.ComposePropertyHelp(wx.GraphicsPen, `en)}

# Operator

# Cast Operation

${help.ComposeConstructorHelp(wx.GraphicsPen, `en)}

${help.ComposeMethodHelp(wx.GraphicsPen, `en)}
)""";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxGraphicsPen
//------------------------------------------------------------------------------
VType_wxGraphicsPen VTYPE_wxGraphicsPen("GraphicsPen");

void VType_wxGraphicsPen::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelp(Gurax_Symbol(en), g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_wxGraphicsObject, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxGraphicsPen
//------------------------------------------------------------------------------
VType& Value_wxGraphicsPen::vtype = VTYPE_wxGraphicsPen;

String Value_wxGraphicsPen::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.GraphicsPen");
}

Gurax_EndModuleScope(wx)
