//==============================================================================
// VType_wxRibbonPage.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXRIBBONPAGE_H
#define GURAX_MODULE_WX_VTYPE_WXRIBBONPAGE_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/ribbon/page.h>
#include "Util.h"
#include "VType_wxRibbonControl.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxRibbonPage
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxRibbonPage : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxRibbonPage VTYPE_wxRibbonPage;

//------------------------------------------------------------------------------
// Value_wxRibbonPage
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxRibbonPage : public Value_wxRibbonControl {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxRibbonPage);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxRibbonPage");
protected:
	wxWeakRef<wxRibbonPage> _pEntity;
public:
	class EntityT : public wxRibbonPage {
	public:
		using wxRibbonPage::wxRibbonPage;
	public:
		EntityCore core_gurax;
	};
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxRibbonPage() = delete;
	explicit Value_wxRibbonPage(wxRibbonPage* pEntity, VType& vtype = VTYPE_wxRibbonPage) :
		Value_wxRibbonControl(pEntity, vtype), _pEntity(pEntity) {}
	// Copy constructor/operator
	Value_wxRibbonPage(const Value_wxRibbonPage& src) = delete;
	Value_wxRibbonPage& operator=(const Value_wxRibbonPage& src) = delete;
	// Move constructor/operator
	Value_wxRibbonPage(Value_wxRibbonPage&& src) noexcept = delete;
	Value_wxRibbonPage& operator=(Value_wxRibbonPage&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxRibbonPage() = default;
public:
	wxRibbonPage& GetEntity() { return *_pEntity; }
	const wxRibbonPage& GetEntity() const { return *_pEntity; }
	wxRibbonPage* GetEntityPtr() { return _pEntity.get(); }
	const wxRibbonPage* GetEntityPtr() const { return _pEntity.get(); }
public:
	static wxRibbonPage& GetEntity(Value& value) {
		return dynamic_cast<Value_wxRibbonPage&>(value).GetEntity();
	}
	static const wxRibbonPage& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxRibbonPage&>(value).GetEntity();
	}
	static wxRibbonPage* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxRibbonPage&>(value).GetEntityPtr();
	}
	static const wxRibbonPage* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxRibbonPage&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
