//==============================================================================
// VTypes.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Assignment
//------------------------------------------------------------------------------
void AssignVTypes(Frame& frame)
{
	frame.Assign(VTYPE_wxApp);
	frame.Assign(VTYPE_wxEventType);
	frame.Assign(VTYPE_wxSetCursorEvent);
	frame.Assign(VTYPE_wxAboutDialogInfo);
	frame.Assign(VTYPE_wxActivateEvent);
	frame.Assign(VTYPE_wxAnyButton);
	frame.Assign(VTYPE_wxAppConsole);
	frame.Assign(VTYPE_wxBoxSizer);
	frame.Assign(VTYPE_wxButton);
	frame.Assign(VTYPE_wxCheckBox);
	frame.Assign(VTYPE_wxChildFocusEvent);
	frame.Assign(VTYPE_wxComboBox);
	frame.Assign(VTYPE_wxCommandEvent);
	frame.Assign(VTYPE_wxContextMenuEvent);
	frame.Assign(VTYPE_wxControl);
	frame.Assign(VTYPE_wxDropFilesEvent);
	frame.Assign(VTYPE_wxEraseEvent);
	frame.Assign(VTYPE_wxEvent);
	frame.Assign(VTYPE_wxEvtHandler);
	frame.Assign(VTYPE_wxFlexGridSizer);
	frame.Assign(VTYPE_wxFocusEvent);
	frame.Assign(VTYPE_wxFrame);
	frame.Assign(VTYPE_wxGridBagSizer);
	frame.Assign(VTYPE_wxGridSizer);
	frame.Assign(VTYPE_wxHelpEvent);
	frame.Assign(VTYPE_wxIdleEvent);
	frame.Assign(VTYPE_wxJoystickEvent);
	frame.Assign(VTYPE_wxKeyEvent);
	frame.Assign(VTYPE_wxMenu);
	frame.Assign(VTYPE_wxMenuBar);
	frame.Assign(VTYPE_wxMenuItem);
	frame.Assign(VTYPE_wxMouseCaptureChangedEvent);
	frame.Assign(VTYPE_wxMouseCaptureLostEvent);
	frame.Assign(VTYPE_wxMouseEvent);
	frame.Assign(VTYPE_wxObject);
	frame.Assign(VTYPE_wxPaintEvent);
	frame.Assign(VTYPE_wxPanel);
	frame.Assign(VTYPE_wxPoint);
	frame.Assign(VTYPE_wxPowerEvent);
	frame.Assign(VTYPE_wxScrollWinEvent);
	frame.Assign(VTYPE_wxSize);
	frame.Assign(VTYPE_wxSizeEvent);
	frame.Assign(VTYPE_wxSizer);
	frame.Assign(VTYPE_wxSizerFlags);
	frame.Assign(VTYPE_wxSizerItem);
	frame.Assign(VTYPE_wxStaticBox);
	frame.Assign(VTYPE_wxStaticBoxSizer);
	frame.Assign(VTYPE_wxStatusBar);
	frame.Assign(VTYPE_wxStdDialogButtonSizer);
	frame.Assign(VTYPE_wxSysColourChangedEvent);
	frame.Assign(VTYPE_wxValidator);
	frame.Assign(VTYPE_wxWindow);
	frame.Assign(VTYPE_wxWrapSizer);
}

Gurax_EndModuleScope(wx)
