//==============================================================================
// VType_wxFlexGridSizer.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"**(
# Overview

# Predefined Variable

# Property

# Operator

# Cast Operation

# Constructor

# Method
)**";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------


//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxFlexGridSizer
//------------------------------------------------------------------------------
VType_wxFlexGridSizer VTYPE_wxFlexGridSizer("FlexGridSizer");

void VType_wxFlexGridSizer::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelpTmpl(Gurax_Symbol(en), g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_wxGridSizer, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxFlexGridSizer
//------------------------------------------------------------------------------
VType& Value_wxFlexGridSizer::vtype = VTYPE_wxFlexGridSizer;

String Value_wxFlexGridSizer::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.FlexGridSizer");
}

Gurax_EndModuleScope(wx)
