//==============================================================================
// VType_wxJoystickEvent.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"**(
# Overview

# Predefined Variable

# Property

# Operator

# Cast Operation

# Constructor

# Method
)**";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxJoystickEvent
//------------------------------------------------------------------------------
VType_wxJoystickEvent VTYPE_wxJoystickEvent("JoystickEvent");

void VType_wxJoystickEvent::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelpTmpl(Gurax_Symbol(en), g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_wxEvent, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxJoystickEvent
//------------------------------------------------------------------------------
VType& Value_wxJoystickEvent::vtype = VTYPE_wxJoystickEvent;
EventValueFactoryDeriv<Value_wxJoystickEvent> Value_wxJoystickEvent::eventValueFactory;

String Value_wxJoystickEvent::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.JoystickEvent");
}

Gurax_EndModuleScope(wx)
