//==============================================================================
// VType_wxPopupWindow.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"**(
# Overview

# Predefined Variable

${help.ComposePropertyHelp(wx.PopupWindow, `en)}

# Operator

# Cast Operation

${help.ComposeConstructorHelp(wx.PopupWindow, `en)}

${help.ComposeMethodHelp(wx.PopupWindow, `en)}
)**";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxPopupWindow
//------------------------------------------------------------------------------
VType_wxPopupWindow VTYPE_wxPopupWindow("PopupWindow");

void VType_wxPopupWindow::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelp(Gurax_Symbol(en), g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_wxNonOwnedWindow, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxPopupWindow
//------------------------------------------------------------------------------
VType& Value_wxPopupWindow::vtype = VTYPE_wxPopupWindow;

String Value_wxPopupWindow::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.PopupWindow");
}

//------------------------------------------------------------------------------
// Value_wxPopupWindow::EntityT
//------------------------------------------------------------------------------

Gurax_EndModuleScope(wx)
