//==============================================================================
// VType_wxRibbonGallery.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXRIBBONGALLERY_H
#define GURAX_MODULE_WX_VTYPE_WXRIBBONGALLERY_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/ribbon/gallery.h>
#include "Util.h"
#include "VType_wxRibbonControl.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxRibbonGallery
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxRibbonGallery : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxRibbonGallery VTYPE_wxRibbonGallery;

//------------------------------------------------------------------------------
// Value_wxRibbonGallery
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxRibbonGallery : public Value_wxRibbonControl {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxRibbonGallery);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxRibbonGallery");
protected:
	wxWeakRef<wxRibbonGallery> _pEntity;
public:
	class EntityT : public wxRibbonGallery {
	public:
		using wxRibbonGallery::wxRibbonGallery;
	public:
		EntityCore core_gurax;
		virtual bool ScrollLines(int lines) override;
		bool public_ScrollLines(int lines) { return wxRibbonGallery::ScrollLines(lines); }
	};
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxRibbonGallery() = delete;
	explicit Value_wxRibbonGallery(wxRibbonGallery* pEntity, VType& vtype = VTYPE_wxRibbonGallery) :
		Value_wxRibbonControl(pEntity, vtype), _pEntity(pEntity) {}
	// Copy constructor/operator
	Value_wxRibbonGallery(const Value_wxRibbonGallery& src) = delete;
	Value_wxRibbonGallery& operator=(const Value_wxRibbonGallery& src) = delete;
	// Move constructor/operator
	Value_wxRibbonGallery(Value_wxRibbonGallery&& src) noexcept = delete;
	Value_wxRibbonGallery& operator=(Value_wxRibbonGallery&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxRibbonGallery() = default;
public:
	wxRibbonGallery& GetEntity() { return *_pEntity; }
	const wxRibbonGallery& GetEntity() const { return *_pEntity; }
	wxRibbonGallery* GetEntityPtr() { return _pEntity.get(); }
	const wxRibbonGallery* GetEntityPtr() const { return _pEntity.get(); }
public:
	static wxRibbonGallery& GetEntity(Value& value) {
		return dynamic_cast<Value_wxRibbonGallery&>(value).GetEntity();
	}
	static const wxRibbonGallery& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxRibbonGallery&>(value).GetEntity();
	}
	static wxRibbonGallery* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxRibbonGallery&>(value).GetEntityPtr();
	}
	static const wxRibbonGallery* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxRibbonGallery&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
