//==============================================================================
// VType_wxMouseEvent.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXMOUSEEVENT_H
#define GURAX_MODULE_WX_VTYPE_WXMOUSEEVENT_H
#include <gurax.h>
#include <wx/wx.h>
#include "Util.h"
#include "VType_wxEvent.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxMouseEvent
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxMouseEvent : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxMouseEvent VTYPE_wxMouseEvent;

//------------------------------------------------------------------------------
// Value_wxMouseEvent
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxMouseEvent : public Value_wxEvent {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxMouseEvent);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxMouseEvent");
public:
	static VType& vtype;
	static EventValueFactoryDeriv<Value_wxMouseEvent> eventValueFactory;
public:
	// Constructor
	Value_wxMouseEvent() = delete;
	Value_wxMouseEvent(wxEvent& entity, Value* pValueUserData, VType& vtype = VTYPE_wxMouseEvent) :
		Value_wxEvent(entity, pValueUserData, vtype) {}
	// Copy constructor/operator
	Value_wxMouseEvent(const Value_wxMouseEvent& src) = delete;
	Value_wxMouseEvent& operator=(const Value_wxMouseEvent& src) = delete;
	// Move constructor/operator
	Value_wxMouseEvent(Value_wxMouseEvent&& src) noexcept = delete;
	Value_wxMouseEvent& operator=(Value_wxMouseEvent&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxMouseEvent() = default;
public:
	wxMouseEvent& GetEntity() { return reinterpret_cast<wxMouseEvent&>(Value_wxEvent::GetEntity()); }
	const wxMouseEvent& GetEntity() const { return reinterpret_cast<const wxMouseEvent&>(Value_wxEvent::GetEntity()); }
	wxMouseEvent* GetEntityPtr() { return reinterpret_cast<wxMouseEvent*>(Value_wxEvent::GetEntityPtr()); }\
	const wxMouseEvent* GetEntityPtr() const { return reinterpret_cast<const wxMouseEvent*>(Value_wxEvent::GetEntityPtr()); }
public:
	static wxMouseEvent& GetEntity(Value& value) {
		return dynamic_cast<Value_wxMouseEvent&>(value).GetEntity();
	}
	static const wxMouseEvent& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxMouseEvent&>(value).GetEntity();
	}
	static wxMouseEvent* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxMouseEvent&>(value).GetEntityPtr();
	}
	static const wxMouseEvent* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxMouseEvent&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
