//==============================================================================
// VType_wxGraphicsBrush.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXGRAPHICSBRUSH_H
#define GURAX_MODULE_WX_VTYPE_WXGRAPHICSBRUSH_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/graphics.h>
#include "Util.h"
#include "VType_wxGraphicsObject.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxGraphicsBrush
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxGraphicsBrush : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxGraphicsBrush VTYPE_wxGraphicsBrush;

//------------------------------------------------------------------------------
// Value_wxGraphicsBrush
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxGraphicsBrush : public Value_wxGraphicsObject {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxGraphicsBrush);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxGraphicsBrush");
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxGraphicsBrush() = delete;
	explicit Value_wxGraphicsBrush(const wxGraphicsBrush& entity, VType& vtype = VTYPE_wxGraphicsBrush) :
		Value_wxGraphicsObject(entity, vtype) {}
	// Copy constructor/operator
	Value_wxGraphicsBrush(const Value_wxGraphicsBrush& src) = delete;
	Value_wxGraphicsBrush& operator=(const Value_wxGraphicsBrush& src) = delete;
	// Move constructor/operator
	Value_wxGraphicsBrush(Value_wxGraphicsBrush&& src) noexcept = delete;
	Value_wxGraphicsBrush& operator=(Value_wxGraphicsBrush&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxGraphicsBrush() = default;
public:
	wxGraphicsBrush& GetEntity() { return reinterpret_cast<wxGraphicsBrush&>(Value_wxGraphicsObject::GetEntity()); }
	const wxGraphicsBrush& GetEntity() const { return reinterpret_cast<const wxGraphicsBrush&>(Value_wxGraphicsObject::GetEntity()); }
	wxGraphicsBrush* GetEntityPtr() { return reinterpret_cast<wxGraphicsBrush*>(Value_wxGraphicsObject::GetEntityPtr()); }\
	const wxGraphicsBrush* GetEntityPtr() const { return reinterpret_cast<const wxGraphicsBrush*>(Value_wxGraphicsObject::GetEntityPtr()); }
public:
	static wxGraphicsBrush& GetEntity(Value& value) {
		return dynamic_cast<Value_wxGraphicsBrush&>(value).GetEntity();
	}
	static const wxGraphicsBrush& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxGraphicsBrush&>(value).GetEntity();
	}
	static wxGraphicsBrush* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxGraphicsBrush&>(value).GetEntityPtr();
	}
	static const wxGraphicsBrush* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxGraphicsBrush&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
