set(SRCFILES_VTYPE
	VType_wxApp.cpp
	VType_wxEventType.cpp
	VType_wxAnyButton.cpp
	VType_wxAppConsole.cpp
	VType_wxButton.cpp
	VType_wxCommandEvent.cpp
	VType_wxControl.cpp
	VType_wxEvent.cpp
	VType_wxEvtHandler.cpp
	VType_wxFrame.cpp
	VType_wxMenu.cpp
	VType_wxMenuBar.cpp
	VType_wxMenuItem.cpp
	VType_wxObject.cpp
	VType_wxPanel.cpp
	VType_wxPoint.cpp
	VType_wxSize.cpp
	VType_wxStatusBar.cpp
	VType_wxValidator.cpp
	VType_wxWindow.cpp
)
