//==============================================================================
// VType_wxHtmlContainerCell.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXHTMLCONTAINERCELL_H
#define GURAX_MODULE_WX_VTYPE_WXHTMLCONTAINERCELL_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/html/htmlcell.h>
#include "Util.h"
#include "VType_wxHtmlCell.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxHtmlContainerCell
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxHtmlContainerCell : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxHtmlContainerCell VTYPE_wxHtmlContainerCell;

//------------------------------------------------------------------------------
// Value_wxHtmlContainerCell
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxHtmlContainerCell : public Value_wxHtmlCell {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxHtmlContainerCell);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxHtmlContainerCell");
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxHtmlContainerCell() = delete;
	explicit Value_wxHtmlContainerCell(const wxHtmlContainerCell& entity, VType& vtype = VTYPE_wxHtmlContainerCell) :
		Value_wxHtmlCell(entity, vtype) {}
	// Copy constructor/operator
	Value_wxHtmlContainerCell(const Value_wxHtmlContainerCell& src) = delete;
	Value_wxHtmlContainerCell& operator=(const Value_wxHtmlContainerCell& src) = delete;
	// Move constructor/operator
	Value_wxHtmlContainerCell(Value_wxHtmlContainerCell&& src) noexcept = delete;
	Value_wxHtmlContainerCell& operator=(Value_wxHtmlContainerCell&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxHtmlContainerCell() = default;
public:
	wxHtmlContainerCell& GetEntity() { return reinterpret_cast<wxHtmlContainerCell&>(Value_wxHtmlCell::GetEntity()); }
	const wxHtmlContainerCell& GetEntity() const { return reinterpret_cast<const wxHtmlContainerCell&>(Value_wxHtmlCell::GetEntity()); }
	wxHtmlContainerCell* GetEntityPtr() { return reinterpret_cast<wxHtmlContainerCell*>(Value_wxHtmlCell::GetEntityPtr()); }\
	const wxHtmlContainerCell* GetEntityPtr() const { return reinterpret_cast<const wxHtmlContainerCell*>(Value_wxHtmlCell::GetEntityPtr()); }
public:
	static wxHtmlContainerCell& GetEntity(Value& value) {
		return dynamic_cast<Value_wxHtmlContainerCell&>(value).GetEntity();
	}
	static const wxHtmlContainerCell& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxHtmlContainerCell&>(value).GetEntity();
	}
	static wxHtmlContainerCell* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxHtmlContainerCell&>(value).GetEntityPtr();
	}
	static const wxHtmlContainerCell* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxHtmlContainerCell&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
