//==============================================================================
// VType_wxBookCtrlBase.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXBOOKCTRLBASE_H
#define GURAX_MODULE_WX_VTYPE_WXBOOKCTRLBASE_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/bookctrl.h>
#include "Util.h"
#include "VType_wxControl.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxBookCtrlBase
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxBookCtrlBase : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxBookCtrlBase VTYPE_wxBookCtrlBase;

//------------------------------------------------------------------------------
// Value_wxBookCtrlBase
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxBookCtrlBase : public Value_wxControl {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxBookCtrlBase);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxBookCtrlBase");
protected:
	wxWeakRef<wxBookCtrlBase> _pEntity;
public:
	class EntityT : public wxBookCtrlBase {
	public:
		using wxBookCtrlBase::wxBookCtrlBase;
	public:
		EntityCore core_gurax;
	};
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxBookCtrlBase() = delete;
	explicit Value_wxBookCtrlBase(wxBookCtrlBase* pEntity, VType& vtype = VTYPE_wxBookCtrlBase) :
		Value_wxControl(pEntity, vtype), _pEntity(pEntity) {}
	// Copy constructor/operator
	Value_wxBookCtrlBase(const Value_wxBookCtrlBase& src) = delete;
	Value_wxBookCtrlBase& operator=(const Value_wxBookCtrlBase& src) = delete;
	// Move constructor/operator
	Value_wxBookCtrlBase(Value_wxBookCtrlBase&& src) noexcept = delete;
	Value_wxBookCtrlBase& operator=(Value_wxBookCtrlBase&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxBookCtrlBase() = default;
public:
	wxBookCtrlBase& GetEntity() { return *_pEntity; }
	const wxBookCtrlBase& GetEntity() const { return *_pEntity; }
	wxBookCtrlBase* GetEntityPtr() { return _pEntity.get(); }
	const wxBookCtrlBase* GetEntityPtr() const { return _pEntity.get(); }
public:
	static wxBookCtrlBase& GetEntity(Value& value) {
		return dynamic_cast<Value_wxBookCtrlBase&>(value).GetEntity();
	}
	static const wxBookCtrlBase& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxBookCtrlBase&>(value).GetEntity();
	}
	static wxBookCtrlBase* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxBookCtrlBase&>(value).GetEntityPtr();
	}
	static const wxBookCtrlBase* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxBookCtrlBase&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
