//==============================================================================
// VType_wxSizerItem.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXSIZERITEM_H
#define GURAX_MODULE_WX_VTYPE_WXSIZERITEM_H
#include <gurax.h>
#include <wx/wx.h>
#include "Util.h"
#include "VType_wxObject.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxSizerItem
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxSizerItem : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxSizerItem VTYPE_wxSizerItem;

//------------------------------------------------------------------------------
// Value_wxSizerItem
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxSizerItem : public Value_wxObject {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxSizerItem);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxSizerItem");
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxSizerItem() = delete;
	explicit Value_wxSizerItem(const wxSizerItem& entity, VType& vtype = VTYPE_wxSizerItem) :
		Value_wxObject(entity, vtype) {}
	// Copy constructor/operator
	Value_wxSizerItem(const Value_wxSizerItem& src) = delete;
	Value_wxSizerItem& operator=(const Value_wxSizerItem& src) = delete;
	// Move constructor/operator
	Value_wxSizerItem(Value_wxSizerItem&& src) noexcept = delete;
	Value_wxSizerItem& operator=(Value_wxSizerItem&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxSizerItem() = default;
public:
	wxSizerItem& GetEntity() { return reinterpret_cast<wxSizerItem&>(Value_wxObject::GetEntity()); }
	const wxSizerItem& GetEntity() const { return reinterpret_cast<const wxSizerItem&>(Value_wxObject::GetEntity()); }
	wxSizerItem* GetEntityPtr() { return reinterpret_cast<wxSizerItem*>(Value_wxObject::GetEntityPtr()); }\
	const wxSizerItem* GetEntityPtr() const { return reinterpret_cast<const wxSizerItem*>(Value_wxObject::GetEntityPtr()); }
public:
	static wxSizerItem& GetEntity(Value& value) {
		return dynamic_cast<Value_wxSizerItem&>(value).GetEntity();
	}
	static const wxSizerItem& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxSizerItem&>(value).GetEntity();
	}
	static wxSizerItem* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxSizerItem&>(value).GetEntityPtr();
	}
	static const wxSizerItem* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxSizerItem&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
