//==============================================================================
// VType_wxTextValidator.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXTEXTVALIDATOR_H
#define GURAX_MODULE_WX_VTYPE_WXTEXTVALIDATOR_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/valtext.h>
#include "Util.h"
#include "VType_wxValidator.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxTextValidator
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxTextValidator : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxTextValidator VTYPE_wxTextValidator;

//------------------------------------------------------------------------------
// Value_wxTextValidator
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxTextValidator : public Value_wxValidator {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxTextValidator);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxTextValidator");
protected:
	wxWeakRef<wxTextValidator> _pEntity;
public:
	class EntityT : public wxTextValidator {
	public:
		using wxTextValidator::wxTextValidator;
	public:
		EntityCore core_gurax;
	};
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxTextValidator() = delete;
	explicit Value_wxTextValidator(wxTextValidator* pEntity, VType& vtype = VTYPE_wxTextValidator) :
		Value_wxValidator(pEntity, vtype), _pEntity(pEntity) {}
	// Copy constructor/operator
	Value_wxTextValidator(const Value_wxTextValidator& src) = delete;
	Value_wxTextValidator& operator=(const Value_wxTextValidator& src) = delete;
	// Move constructor/operator
	Value_wxTextValidator(Value_wxTextValidator&& src) noexcept = delete;
	Value_wxTextValidator& operator=(Value_wxTextValidator&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxTextValidator() = default;
public:
	wxTextValidator& GetEntity() { return *_pEntity; }
	const wxTextValidator& GetEntity() const { return *_pEntity; }
	wxTextValidator* GetEntityPtr() { return _pEntity.get(); }
	const wxTextValidator* GetEntityPtr() const { return _pEntity.get(); }
public:
	static wxTextValidator& GetEntity(Value& value) {
		return dynamic_cast<Value_wxTextValidator&>(value).GetEntity();
	}
	static const wxTextValidator& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxTextValidator&>(value).GetEntity();
	}
	static wxTextValidator* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxTextValidator&>(value).GetEntityPtr();
	}
	static const wxTextValidator* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxTextValidator&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
