//==============================================================================
// VType_wxGBPosition.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"**(
# Overview

# Predefined Variable

# Property

# Operator

# Cast Operation

# Constructor

# Method
)**";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxGBPosition
//------------------------------------------------------------------------------
VType_wxGBPosition VTYPE_wxGBPosition("GBPosition");

void VType_wxGBPosition::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelpTmpl(Gurax_Symbol(en), g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_Object, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxGBPosition
//------------------------------------------------------------------------------
VType& Value_wxGBPosition::vtype = VTYPE_wxGBPosition;

String Value_wxGBPosition::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.GBPosition");
}

Gurax_EndModuleScope(wx)
