//==============================================================================
// VType_wxInputStream.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"**(
# Overview

# Predefined Variable

${help.ComposePropertyHelp(wx.InputStream, `en)}

# Operator

# Cast Operation

${help.ComposeConstructorHelp(wx.InputStream, `en)}

${help.ComposeMethodHelp(wx.InputStream, `en)}
)**";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxInputStream
//------------------------------------------------------------------------------
VType_wxInputStream VTYPE_wxInputStream("InputStream");

void VType_wxInputStream::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelp(Gurax_Symbol(en), g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_wxStreamBase, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxInputStream
//------------------------------------------------------------------------------
VType& Value_wxInputStream::vtype = VTYPE_wxInputStream;

String Value_wxInputStream::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.InputStream");
}

Gurax_EndModuleScope(wx)
