//==============================================================================
// VType_wxMask.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"**(
# Overview

# Predefined Variable

${help.ComposePropertyHelp(wx.Mask, `en)}

# Operator

# Cast Operation

${help.ComposeConstructorHelp(wx.Mask, `en)}

${help.ComposeMethodHelp(wx.Mask, `en)}
)**";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxMask
//------------------------------------------------------------------------------
VType_wxMask VTYPE_wxMask("Mask");

void VType_wxMask::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelp("en", g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_wxObject, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxMask
//------------------------------------------------------------------------------
VType& Value_wxMask::vtype = VTYPE_wxMask;

String Value_wxMask::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.Mask");
}

Gurax_EndModuleScope(wx)
