//==============================================================================
// VType_wxMoveEvent.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXMOVEEVENT_H
#define GURAX_MODULE_WX_VTYPE_WXMOVEEVENT_H
#include <gurax.h>
#include <wx/wx.h>
#include "Util.h"
#include "VType_wxEvent.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxMoveEvent
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxMoveEvent : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxMoveEvent VTYPE_wxMoveEvent;

//------------------------------------------------------------------------------
// Value_wxMoveEvent
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxMoveEvent : public Value_wxEvent {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxMoveEvent);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxMoveEvent");
public:
	static VType& vtype;
	static EventValueFactoryDeriv<Value_wxMoveEvent> eventValueFactory;
public:
	// Constructor
	Value_wxMoveEvent() = delete;
	Value_wxMoveEvent(wxEvent& entity, Value* pValueUserData, VType& vtype = VTYPE_wxMoveEvent) :
		Value_wxEvent(entity, pValueUserData, vtype) {}
	// Copy constructor/operator
	Value_wxMoveEvent(const Value_wxMoveEvent& src) = delete;
	Value_wxMoveEvent& operator=(const Value_wxMoveEvent& src) = delete;
	// Move constructor/operator
	Value_wxMoveEvent(Value_wxMoveEvent&& src) noexcept = delete;
	Value_wxMoveEvent& operator=(Value_wxMoveEvent&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxMoveEvent() = default;
public:
	wxMoveEvent& GetEntity() { return reinterpret_cast<wxMoveEvent&>(Value_wxEvent::GetEntity()); }
	const wxMoveEvent& GetEntity() const { return reinterpret_cast<const wxMoveEvent&>(Value_wxEvent::GetEntity()); }
	wxMoveEvent* GetEntityPtr() { return reinterpret_cast<wxMoveEvent*>(Value_wxEvent::GetEntityPtr()); }\
	const wxMoveEvent* GetEntityPtr() const { return reinterpret_cast<const wxMoveEvent*>(Value_wxEvent::GetEntityPtr()); }
public:
	static wxMoveEvent& GetEntity(Value& value) {
		return dynamic_cast<Value_wxMoveEvent&>(value).GetEntity();
	}
	static const wxMoveEvent& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxMoveEvent&>(value).GetEntity();
	}
	static wxMoveEvent* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxMoveEvent&>(value).GetEntityPtr();
	}
	static const wxMoveEvent* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxMoveEvent&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
