//==============================================================================
// VType_wxHelpEvent.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXHELPEVENT_H
#define GURAX_MODULE_WX_VTYPE_WXHELPEVENT_H
#include <gurax.h>
#include <wx/wx.h>
#include "Util.h"
#include "VType_wxCommandEvent.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxHelpEvent
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxHelpEvent : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxHelpEvent VTYPE_wxHelpEvent;

//------------------------------------------------------------------------------
// Value_wxHelpEvent
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxHelpEvent : public Value_wxCommandEvent {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxHelpEvent);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxHelpEvent");
public:
	static VType& vtype;
	static EventValueFactoryDeriv<Value_wxHelpEvent> eventValueFactory;
public:
	// Constructor
	Value_wxHelpEvent() = delete;
	Value_wxHelpEvent(wxEvent& entity, Value* pValueUserData, VType& vtype = VTYPE_wxHelpEvent) :
		Value_wxCommandEvent(entity, pValueUserData, vtype) {}
	// Copy constructor/operator
	Value_wxHelpEvent(const Value_wxHelpEvent& src) = delete;
	Value_wxHelpEvent& operator=(const Value_wxHelpEvent& src) = delete;
	// Move constructor/operator
	Value_wxHelpEvent(Value_wxHelpEvent&& src) noexcept = delete;
	Value_wxHelpEvent& operator=(Value_wxHelpEvent&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxHelpEvent() = default;
public:
	wxHelpEvent& GetEntity() { return reinterpret_cast<wxHelpEvent&>(Value_wxCommandEvent::GetEntity()); }
	const wxHelpEvent& GetEntity() const { return reinterpret_cast<const wxHelpEvent&>(Value_wxCommandEvent::GetEntity()); }
	wxHelpEvent* GetEntityPtr() { return reinterpret_cast<wxHelpEvent*>(Value_wxCommandEvent::GetEntityPtr()); }\
	const wxHelpEvent* GetEntityPtr() const { return reinterpret_cast<const wxHelpEvent*>(Value_wxCommandEvent::GetEntityPtr()); }
public:
	static wxHelpEvent& GetEntity(Value& value) {
		return dynamic_cast<Value_wxHelpEvent&>(value).GetEntity();
	}
	static const wxHelpEvent& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxHelpEvent&>(value).GetEntity();
	}
	static wxHelpEvent* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxHelpEvent&>(value).GetEntityPtr();
	}
	static const wxHelpEvent* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxHelpEvent&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
