//==============================================================================
// VType_wxRichTextStyleListCtrl.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"**(
# Overview

# Predefined Variable

# Property

# Operator

# Cast Operation

# Constructor

# Method
)**";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxRichTextStyleListCtrl
//------------------------------------------------------------------------------
VType_wxRichTextStyleListCtrl VTYPE_wxRichTextStyleListCtrl("RichTextStyleListCtrl");

void VType_wxRichTextStyleListCtrl::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelpTmpl(Gurax_Symbol(en), g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_wxControl, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxRichTextStyleListCtrl
//------------------------------------------------------------------------------
VType& Value_wxRichTextStyleListCtrl::vtype = VTYPE_wxRichTextStyleListCtrl;

String Value_wxRichTextStyleListCtrl::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.RichTextStyleListCtrl");
}

//------------------------------------------------------------------------------
// Value_wxRichTextStyleListCtrl::EntityT
//------------------------------------------------------------------------------

Gurax_EndModuleScope(wx)
