//==============================================================================
// VType_wxDocChildFrame.cpp
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#include "stdafx.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// Help
//------------------------------------------------------------------------------
static const char* g_docHelp_en = u8R"**(
# Overview

# Predefined Variable

${help.ComposePropertyHelp(wx.DocChildFrame, `en)}

# Operator

# Cast Operation

${help.ComposeConstructorHelp(wx.DocChildFrame, `en)}

${help.ComposeMethodHelp(wx.DocChildFrame, `en)}
)**";

//------------------------------------------------------------------------------
// Implementation of constructor
//------------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of method
//-----------------------------------------------------------------------------

//-----------------------------------------------------------------------------
// Implementation of property
//-----------------------------------------------------------------------------

//------------------------------------------------------------------------------
// VType_wxDocChildFrame
//------------------------------------------------------------------------------
VType_wxDocChildFrame VTYPE_wxDocChildFrame("DocChildFrame");

void VType_wxDocChildFrame::DoPrepare(Frame& frameOuter)
{
	// Add help
	AddHelp(Gurax_Symbol(en), g_docHelp_en);
	// Declaration of VType
	Declare(VTYPE_wxFrame, Flag::Mutable);
	// Assignment of method
}

//------------------------------------------------------------------------------
// Value_wxDocChildFrame
//------------------------------------------------------------------------------
VType& Value_wxDocChildFrame::vtype = VTYPE_wxDocChildFrame;

String Value_wxDocChildFrame::ToString(const StringStyle& ss) const
{
	return ToStringGeneric(ss, "wx.DocChildFrame");
}

//------------------------------------------------------------------------------
// Value_wxDocChildFrame::EntityT
//------------------------------------------------------------------------------

Gurax_EndModuleScope(wx)
