//==============================================================================
// VType_wxSystemColourProperty.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXSYSTEMCOLOURPROPERTY_H
#define GURAX_MODULE_WX_VTYPE_WXSYSTEMCOLOURPROPERTY_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/propgrid/advprops.h>
#include "Util.h"
#include "VType_wxEnumProperty.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxSystemColourProperty
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxSystemColourProperty : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxSystemColourProperty VTYPE_wxSystemColourProperty;

//------------------------------------------------------------------------------
// Value_wxSystemColourProperty
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxSystemColourProperty : public Value_wxEnumProperty {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxSystemColourProperty);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxSystemColourProperty");
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxSystemColourProperty() = delete;
	explicit Value_wxSystemColourProperty(const wxSystemColourProperty& entity, VType& vtype = VTYPE_wxSystemColourProperty) :
		Value_wxEnumProperty(entity, vtype) {}
	// Copy constructor/operator
	Value_wxSystemColourProperty(const Value_wxSystemColourProperty& src) = delete;
	Value_wxSystemColourProperty& operator=(const Value_wxSystemColourProperty& src) = delete;
	// Move constructor/operator
	Value_wxSystemColourProperty(Value_wxSystemColourProperty&& src) noexcept = delete;
	Value_wxSystemColourProperty& operator=(Value_wxSystemColourProperty&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxSystemColourProperty() = default;
public:
	wxSystemColourProperty& GetEntity() { return reinterpret_cast<wxSystemColourProperty&>(Value_wxEnumProperty::GetEntity()); }
	const wxSystemColourProperty& GetEntity() const { return reinterpret_cast<const wxSystemColourProperty&>(Value_wxEnumProperty::GetEntity()); }
	wxSystemColourProperty* GetEntityPtr() { return reinterpret_cast<wxSystemColourProperty*>(Value_wxEnumProperty::GetEntityPtr()); }\
	const wxSystemColourProperty* GetEntityPtr() const { return reinterpret_cast<const wxSystemColourProperty*>(Value_wxEnumProperty::GetEntityPtr()); }
public:
	static wxSystemColourProperty& GetEntity(Value& value) {
		return dynamic_cast<Value_wxSystemColourProperty&>(value).GetEntity();
	}
	static const wxSystemColourProperty& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxSystemColourProperty&>(value).GetEntity();
	}
	static wxSystemColourProperty* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxSystemColourProperty&>(value).GetEntityPtr();
	}
	static const wxSystemColourProperty* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxSystemColourProperty&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
