//==============================================================================
// VType_wxPGChoiceEditor.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXPGCHOICEEDITOR_H
#define GURAX_MODULE_WX_VTYPE_WXPGCHOICEEDITOR_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/propgrid/editors.h>
#include "Util.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxPGChoiceEditor
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxPGChoiceEditor : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxPGChoiceEditor VTYPE_wxPGChoiceEditor;

//------------------------------------------------------------------------------
// Value_wxPGChoiceEditor
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxPGChoiceEditor : public Value_Object {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxPGChoiceEditor);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxPGChoiceEditor");
protected:
	wxPGChoiceEditor _entity;
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxPGChoiceEditor() = delete;
	explicit Value_wxPGChoiceEditor(const wxPGChoiceEditor& entity, VType& vtype = VTYPE_wxPGChoiceEditor) :
		Value_Object(vtype), _entity(entity) {}
	// Copy constructor/operator
	Value_wxPGChoiceEditor(const Value_wxPGChoiceEditor& src) = delete;
	Value_wxPGChoiceEditor& operator=(const Value_wxPGChoiceEditor& src) = delete;
	// Move constructor/operator
	Value_wxPGChoiceEditor(Value_wxPGChoiceEditor&& src) noexcept = delete;
	Value_wxPGChoiceEditor& operator=(Value_wxPGChoiceEditor&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxPGChoiceEditor() = default;
public:
	wxPGChoiceEditor& GetEntity() { return _entity; }
	const wxPGChoiceEditor& GetEntity() const { return _entity; }
	wxPGChoiceEditor* GetEntityPtr() { return &_entity; }
	const wxPGChoiceEditor* GetEntityPtr() const { return &_entity; }
public:
	static wxPGChoiceEditor& GetEntity(Value& value) {
		return dynamic_cast<Value_wxPGChoiceEditor&>(value).GetEntity();
	}
	static const wxPGChoiceEditor& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxPGChoiceEditor&>(value).GetEntity();
	}
	static wxPGChoiceEditor* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxPGChoiceEditor&>(value).GetEntityPtr();
	}
	static const wxPGChoiceEditor* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxPGChoiceEditor&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
