//==============================================================================
// VType_wxDataViewCtrl.h
// Don't edit this file since it's been generated by Generate.gura.
//==============================================================================
#ifndef GURAX_MODULE_WX_VTYPE_WXDATAVIEWCTRL_H
#define GURAX_MODULE_WX_VTYPE_WXDATAVIEWCTRL_H
#include <gurax.h>
#include <wx/wx.h>
#include <wx/dataview.h>
#include "Util.h"
#include "VType_wxControl.h"

Gurax_BeginModuleScope(wx)

//------------------------------------------------------------------------------
// VType_wxDataViewCtrl
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE VType_wxDataViewCtrl : public VType {
public:
	using VType::VType;
	virtual void DoPrepare(Frame& frameOuter) override;
};

extern GURAX_DLLDECLARE VType_wxDataViewCtrl VTYPE_wxDataViewCtrl;

//------------------------------------------------------------------------------
// Value_wxDataViewCtrl
//------------------------------------------------------------------------------
class GURAX_DLLDECLARE Value_wxDataViewCtrl : public Value_wxControl {
public:
	// Referable declaration
	Gurax_DeclareReferable(Value_wxDataViewCtrl);
	// Uses MemoryPool allocator
	Gurax_MemoryPoolAllocator("Value_wxDataViewCtrl");
protected:
	wxWeakRef<wxDataViewCtrl> _pEntity;
public:
	class EntityT : public wxDataViewCtrl {
	public:
		using wxDataViewCtrl::wxDataViewCtrl;
	public:
		EntityCore core_gurax;
	};
public:
	static VType& vtype;
public:
	// Constructor
	Value_wxDataViewCtrl() = delete;
	explicit Value_wxDataViewCtrl(wxDataViewCtrl* pEntity, VType& vtype = VTYPE_wxDataViewCtrl) :
		Value_wxControl(pEntity, vtype), _pEntity(pEntity) {}
	// Copy constructor/operator
	Value_wxDataViewCtrl(const Value_wxDataViewCtrl& src) = delete;
	Value_wxDataViewCtrl& operator=(const Value_wxDataViewCtrl& src) = delete;
	// Move constructor/operator
	Value_wxDataViewCtrl(Value_wxDataViewCtrl&& src) noexcept = delete;
	Value_wxDataViewCtrl& operator=(Value_wxDataViewCtrl&& src) noexcept = delete;
protected:
	// Destructor
	~Value_wxDataViewCtrl() = default;
public:
	wxDataViewCtrl& GetEntity() { return *_pEntity; }
	const wxDataViewCtrl& GetEntity() const { return *_pEntity; }
	wxDataViewCtrl* GetEntityPtr() { return _pEntity.get(); }
	const wxDataViewCtrl* GetEntityPtr() const { return _pEntity.get(); }
public:
	static wxDataViewCtrl& GetEntity(Value& value) {
		return dynamic_cast<Value_wxDataViewCtrl&>(value).GetEntity();
	}
	static const wxDataViewCtrl& GetEntity(const Value& value) {
		return dynamic_cast<const Value_wxDataViewCtrl&>(value).GetEntity();
	}
	static wxDataViewCtrl* GetEntityPtr(Value& value) {
		return dynamic_cast<Value_wxDataViewCtrl&>(value).GetEntityPtr();
	}
	static const wxDataViewCtrl* GetEntityPtr(const Value& value) {
		return dynamic_cast<const Value_wxDataViewCtrl&>(value).GetEntityPtr();
	}
public:
	// Virtual functions of Value
	virtual Value* Clone() const override { return Reference(); }
	virtual size_t DoCalcHash() const override {
		return reinterpret_cast<size_t>(GetEntityPtr(*this));
	}
	virtual bool IsEqualTo(const Value& value) const override {
		return IsSameType(value) && GetEntityPtr(*this) == GetEntityPtr(value);
	}
	virtual bool IsLessThan(const Value& value) const override {
		return IsSameType(value)?
			(GetEntityPtr(*this) < GetEntityPtr(value)) :
			GetVTypeCustom().IsLessThan(value.GetVTypeCustom());
	}
	virtual String ToString(const StringStyle& ss) const override;
};

Gurax_EndModuleScope(wx)

#endif
