#!/bin/bash
cases=
cases="$cases DateTime"
cases="$cases DeclCallable"
cases="$cases Function"
cases="$cases Help"
cases="$cases Iterator"
#cases="$cases MemoryPool"
cases="$cases Parser"
cases="$cases Random"
cases="$cases Referable"
cases="$cases SizeOf"
cases="$cases Stream"
cases="$cases String"
cases="$cases Symbol"
cases="$cases Tokenizer"
cases="$cases Value"

if [ $# -eq 0 ]; then
	echo "usage: tester all/casename [update]"
	exit
fi
options=""
if [ "$1" != "all" ]; then
	cases="$1"
	options="--detail"
fi
if [ $# -eq 1 ]; then
	for case in $cases
	do
		echo "$case"
		./unittest $case > result/test-$case.result.txt
		gura diff-result.gura $options result/test-$case.expect.txt result/test-$case.result.txt
	done	
elif [ "$2" = "update" ]; then
	for case in $cases
	do
		echo "update: $case"
		./unittest $case > result/test-$case.expect.txt
	done
fi
